### ISSUE TITLE
Unable to use atempo in audio filter

### ISSUE THREAD

**Issue by parth510** [protonemedia/laravel-ffmpeg#218]
Hello,
I've been trying to increase audio playback speed via FFMPEG. I've found a command mainly "atempo " in ffmpeg which can be executed directly but i'm unable to run the same command using your wrapper in laravel. So it would be great if you can help me out.

For EXA : ffmpeg -i input.mkv -filter:a "atempo=2.0" -vn output.mkv

I want to use atempo to increase audio playback speed but couldn't.

Thanks

**Comment by pascalbaljet** [comment]
You can use a [custom filter](https://github.com/protonemedia/laravel-ffmpeg#custom-filters):

```php
FFMpeg::fromDisk('videos')
    ->open('input.mkv')
    ->addFilter('-af', 'atempo=2.0');
```
