### ISSUE TITLE
Possibility to process online video

### ISSUE THREAD

**Issue by tiaxter** [protonemedia/laravel-ffmpeg#219]
It should be implemented a way to process online video without download them. FFMPEG can already process online video from URL.

**Comment by tiaxter** [comment]
Yes, I'd like to use HTTP(s) protocol with Laravel-FFmpeg.

**Comment by pascalbaljet** [comment]
PR: https://github.com/protonemedia/laravel-ffmpeg/pull/232

**Comment by pascalbaljet** [comment]
Merged in v7.2.0
