### ISSUE TITLE
HLS Key

### ISSUE THREAD

**Issue by kennysinkeler** [protonemedia/laravel-ffmpeg#221]
Hi,
I want add a key, to my HLS stream.  
How can i do that with this package?

**Comment by pascalbaljet** [comment]
You probably need to pass additional parameters to each format you add to the HLS exporter. I haven't tried it myself, but it's something I want to support in the future. You can use the `setAdditionalParameters` method to do that:

```php
$lowBitrate = (new X264)->setAdditionalParameters([
    ...
]);

$midBitrate = (new X264)->setAdditionalParameters([
    ...
]);

$highBitrate = (new X264)->setAdditionalParameters([
    ...
]);
```

**Comment by pascalbaljet** [comment]
It's been a while, but for future visitors of this issue: v7.5 supports encrypted HLS.
