### ISSUE TITLE
How to use with RTSP?

### ISSUE THREAD

**Issue by deepnees** [protonemedia/laravel-ffmpeg#224]
Hi,

I couldn't find any way to use this package with the RTSP URL. FFMpeg supports RTSP URLs but this package seems like only work with local files. I have managed to change the FFMpeg::open method and it worked but it doesn't create an m3u8 file because its live video and keeps create chunk files. I would like to know how to use RTSP live video recording?

**Comment by pascalbaljet** [comment]
So if I understand correctly, you want a long-running PHP process that runs FFmpeg so you can record a live recording of an RTSP stream?

**Comment by deepnees** [comment]
Yes, I have a stream live video, and it records daily. It worked with version 6.0. My player regularly calls m3u8 file and gets new chucks but with version 7 it's not possible. Is there any way to create an m3u8 file first and add new chucks to it.

**Comment by pascalbaljet** [comment]
Could you test this with the new `openUrl` method? Requires v7.2 or higher.

https://github.com/protonemedia/laravel-ffmpeg#open-files-from-the-web
