### ISSUE TITLE
Extracting shot detection timestamps, nothing else

### ISSUE THREAD

**Issue by giulioprovasi** [protonemedia/laravel-ffmpeg#225]
Hey, I am using this cool bindings on my laravel project and I managed to do anything I wanted to, but I am facing a little issue here:

I want to be able to extract scenes (only data, no actual frames) from a media, ffmpeg command would be something like

```
ffmpeg -i $file -filter:v "select='gt(scene,$diff)',showinfo" -f null - 2>&1 | \
    grep Parsed_showinfo | \
    grep pts_time:[0-9.]* -o | \
    grep "[0-9]*\.[0-9]*" -o
```
which outputs some timestamps with scene changes : 

```
1.4
3.44
6.64
7.72
...
```

Is there a way of getting through this with these bindings ?

**Comment by pascalbaljet** [comment]
Could you provide me with some sample data? What is `$diff`?
