### ISSUE TITLE
Errors with .mov / .wmv

### ISSUE THREAD

**Issue by ilgala** [protonemedia/laravel-ffmpeg#226]
Hi!
I've created a chunk uploader for large videos. I making some tests and that's the code I'm using for the chunks' merge process:

```php
$exporter = FFMpeg::fromDisk($this->getChunksDisk())
    ->open($this->mapChunksToArray())
    ->export()
    ->inFormat($this->guessFormat())
    ->concatWithoutTranscoding();

if (! empty($visibility = $this->visibility())) {
    $exporter->withVisibility($visibility);
}

$exporter->toDisk(
    $this->manager->getMergeDisk()
)->save($this->destination);
```

Where `$this->mapChunksToArray()` Retrieves the chunks' paths of a remote or local disk depending on `$this->getChunksDisk()`. The result is something similar to

```php
[
    'my/local/or/remote/path/to/0_chunk.ext',
    'my/local/or/remote/path/to/1_chunk.ext',
    'my/local/or/remote/path/to/2_chunk.ext',
    'my/local/or/remote/path/to/3_chunk.ext',
    // [...]
]
```

The method `$this->guessFormat()` checks the extension of `$this->destination` (the final file path) on a remote or local disk depending on `$this->getMergeDisk()`. At the moment `$this->destination` is always a file with .mp4 extension, I haven't tried any other extension mostly because I don't need it.

The problems, anyway, come out when I try to upload a .mov video or a .wmv video. For .mov video I receive this error:

> FFMpeg/Exception/RuntimeException with message 'Unable to probe /tmp/1181168267-0391084001599064770/chunky/chunks/64bf365c-5de7-4bb4-8e28-f469a82c004a/0_f41dcb983d6c4-sample-1280x720.mov

And for the .wmv video I receive this other error:

> Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/bin/ffmpeg' '-f' 'concat' '-safe' '0' '-i' '/tmp/ffmpeg-concatFcA2YK' '-c' 'copy' '/tmp/741121074-0423914001599065296/chunky/final_file.mp4

*If you need a more detailed output let me know*

I state that I'm not a video expert and my knowledge about codecs and other "video making stuff" it's next to 0... So my main question is:

Have I been too generic? Should I adopt a different merge strategy depending on the file extension? Or it's another kind of problem?

Thanks in advance

**Comment by pascalbaljet** [comment]
I think you should merge the chunks before using FFmpeg. I think FFmpeg doesn't work with the chunks as these chunks are probably invalid on their own.
