### ISSUE TITLE
Return value of ProtoneMedia\LaravelFFMpeg\Drivers\PHPFFMpeg::getDurationInMiliseconds() must be of the type int

### ISSUE THREAD

**Issue by jhemmmm** [protonemedia/laravel-ffmpeg#229]
![image](https://user-images.githubusercontent.com/14343151/92254187-14230080-ef03-11ea-8f6d-b27847240ad8.png)

**Comment by pascalbaljet** [comment]
It seems your media file doesn't have a stream or format that can be detected by FFmpeg. Can you share the media file?
