### ISSUE TITLE
SRT file

### ISSUE THREAD

**Issue by vahidzoli** [protonemedia/laravel-ffmpeg#230]
hi, is there any option in transcode for adding srt subtitle files?

**Comment by pascalbaljet** [comment]
Did you try the [multiple inputs](https://github.com/protonemedia/laravel-ffmpeg#multiple-inputs) feature? Try mapping the subtitles with the `ProtoneMedia\LaravelFFMpeg\FFMpeg\CopyFormat`.

**Comment by Delaney** [comment]
I achieved this using a custom filter.

Example:
```$customFilter = new \FFMpeg\Filters\Video\CustomFilter("subtitles=storage/app/subtitles/1611425569_SyC7lbfQ.srt:fontsdir=storage/fonts:force_style='fontname=source sans pro,Fontsize=16,PrimaryColour=3342591,");```

**Comment by martinzuro** [comment]
@pascalbaljet could you provide me an example for adding two inputs (one .mp4 and one .srt) and then adding the subtitles to the video? Thank you!

**Comment by mstfkhazaal** [comment]
please any example
