### ISSUE TITLE
No sound after compression on Iphone

### ISSUE THREAD

**Issue by Kulaxyz** [protonemedia/laravel-ffmpeg#233]
After compression on ios devices videos play without sound. On other devices it`s ok. Here is my code:
```
$lowBitrateFormat = (new X264('aac', 'libx264'))->setKiloBitrate(700);

        FFMpeg::fromDisk($this->video->disk)
            ->open($this->video->path)
            ->addFilter(function ($filters) {
                $filters->clip(TimeCode::fromSeconds(0), TimeCode::fromSeconds(30));
            })
            ->export()
            ->toDisk('local')
            ->inFormat($lowBitrateFormat)
            ->save('public/downloadable/'.$this->video->id . '.mp4');

```

**Comment by pascalbaljet** [comment]
I executed your example code and I get sound on iOS 14.1. I'm running ffmpeg 4.3.1 installed via brew (default configuration). Probably a problem with your ffmpeg build or maybe your iOS device.

**Comment by indaneey** [comment]
> After compression on ios devices videos play without sound. On other devices it`s ok. Here is my code:
> 
> ```
> $lowBitrateFormat = (new X264('aac', 'libx264'))->setKiloBitrate(700);
> 
>         FFMpeg::fromDisk($this->video->disk)
>             ->open($this->video->path)
>             ->addFilter(function ($filters) {
>                 $filters->clip(TimeCode::fromSeconds(0), TimeCode::fromSeconds(30));
>             })
>             ->export()
>             ->toDisk('local')
>             ->inFormat($lowBitrateFormat)
>             ->save('public/downloadable/'.$this->video->id . '.mp4');
> ```

Please did you resolved this issue?
