### ISSUE TITLE
Convert Audio to Video (with Poster) and Convert Audio for HLS

### ISSUE THREAD

**Issue by mohsen-zanjani** [protonemedia/laravel-ffmpeg#234]
Hello
I could not find the answers to my questions so I am asking them here and I hope someone can help me.

1. How can I convert an **audio** file (wav, mp3, etc.) to a **video** file (mp4) using this package (with an image as a poster)?
```
// something like this command
ffmpeg -loop 1 -i image.jpg -i audio.wav -c:v libx264 -tune stillimage -c:a aac -b:a 192k -pix_fmt yuv420p -shortest out.mp4
```

2. How can I convert an audio file (wav, mp3, etc.) to **HLS** using this package? 
    - I did this correctly for the video file and I had no problem but I did not see a sample for the audio file.
    - Is it possible to stream an audio file and convert it to HLS (making ts and m3u8 files)? I mean, do I need to create HLS files to stream audio files on players like Video.js? Does streaming an audio file make sense?
    -  Do we need to convert the audio file to a video file first and then build the HLS, or can we build the HLS directly?

3. With this package, can a **watermark** be placed on a **photo**? Or wrote a **text** on it (drawtext command)?

4. How to add **album art** (jpg) to audio file (mp3) using this package?
```
// something like this command
ffmpeg -i in.mp3 -i test.png -map 0:0 -map 1:0 -c copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" out.mp3
```

If you provide a sample code of this package for the above three questions, I would be grateful.
Thank You

**Comment by pascalbaljet** [comment]
1. Look into the timelapse feature: https://github.com/protonemedia/laravel-ffmpeg#create-a-timelapse
2. The `HlsExporter` requires a `VideoFormat` so audio-only won't work. I'll look into supporting this.
3. Why would you want to do this with this package?
4. https://github.com/protonemedia/laravel-ffmpeg/issues/237
