### ISSUE TITLE
Encoding failed 

### ISSUE THREAD

**Issue by crazynds** [protonemedia/laravel-ffmpeg#236]
Hello,
I have a problem using the library.
All the things I do return an Encoding failed error.

Im using the windows 10 with laragon to run this project.
The ffmpeg binaries are installed in my pc and configured in the path.

The error:
![image](https://user-images.githubusercontent.com/36674096/95391851-26130d00-08ce-11eb-9d43-65124ed14a50.png)

The code:
![image](https://user-images.githubusercontent.com/36674096/95391982-5fe41380-08ce-11eb-8e25-ffae85464563.png)
![image](https://user-images.githubusercontent.com/36674096/95391869-30350b80-08ce-11eb-8a78-c7b39cb9a5a5.png)

The .env:
![image](https://user-images.githubusercontent.com/36674096/95391888-39be7380-08ce-11eb-9b2d-04c29880b4d8.png)

**Comment by nabilanam** [comment]
this is a late reply but for anyone who gets stuck on this: you need to install libfdk_aac and aac enabled ffmpeg to make this work

**Comment by pascalbaljet** [comment]
https://github.com/protonemedia/laravel-ffmpeg/wiki/FFmpeg-failed-to-execute-command
