### ISSUE TITLE
How to add album art on audio file?

### ISSUE THREAD

**Issue by mohsen-zanjani** [protonemedia/laravel-ffmpeg#237]
Hi, I've been stuck to add album art on mp3 files.
The following code works correctly ...

`ffmpeg -i in.mp3 -i test.png -map 0:0 -map 1:0 -c copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" out.mp3`

The equivalent of this command also works well in laravel-ffmpeg

```php
FFMpeg::fromDisk('public')
    ->open('test.mp3')
    ->addFilter('-i', 'C:\laragon\www\ffmpeg-new\storage\app\public\test.jpg')
    ->addFilter('-map', '0:0')
    ->addFilter('-map', '1:0')
    ->addFilter('-c', 'copy')
    ->addFilter('-id3v2_version', 3)
    ->addFilter('-metadata:s:v', 'title="Album cover"')
    ->addFilter('-metadata:s:v', 'comment="Cover (front)"')
    ->export()
    ->toDisk('public')
    ->save('out.mp3');
```

But I also want to open the **image file from disk**. To do this, I use the following code. But I do not know how to add additional filters in this case. Without these filters, the photo will not be added as an art album. addFilter does not work in this mode ...

```php
FFMpeg::fromDisk('public')
    ->open(['test.mp3', 'test.jpg'])
    ->export()
    ->addFormatOutputMapping(new \ProtoneMedia\LaravelFFMpeg\FFMpeg\CopyFormat,
            Media::make('public', 'out.mp3'),
            ['0:0', '1:0'])
    ->save();
```

**Comment by pascalbaljet** [comment]
When you're opening multiple files, you can set additional parameters with the `setAdditionalParameters` method. There is a `setInitialParameters` method as well. Both are undocumented as they are features of the underlying library. I'll put it somewhere in the docs :)

```php
FFMpeg::fromDisk('public')
    ->open(['test.mp3', 'test.jpg'])
    ->export()
    ->setAdditionalParameters([
        '-id3v2_version', 3,
        '-metadata:s:v', 'title="Album cover"',
        '-metadata:s:v', 'comment="Cover (front)"',
    ])
    ->addFormatOutputMapping(
        new CopyFormat,
        Media::make('public', 'out.mp3'),
        ['0:0', '1:0']
    );
```
