### ISSUE TITLE
Encoding failed with file higher than 15MB

### ISSUE THREAD

**Issue by bruno9520** [protonemedia/laravel-ffmpeg#241]
Hi, i have a problem, when i upload files lower than 15MB the job works fine but when i upload a file higher than 15MB the job trow an error of encoding failed

`
        public function handle()    {

        $format = new X264();
        $format->setAudioCodec('libmp3lame');
        $format->setVideoCodec('libx264');
        $format->setKiloBitrate(1000);
        $name1 = $this->getCleanFileName($this->multimedia->file);
        $converted_name = $this->getCleanFileName2($name1);

        FFMpeg::fromDisk('s3')
            ->open($name1)
            ->addFilter(function ($filters) {
                $filters->resize(new Dimension(960, 540));
            })
            ->export()
            ->toDisk('s3')
            ->inFormat($format)
            ->save($converted_name . '_re_.mp4');
        
        $this->multimedia->update([
            'file' => 'xxxxxxxx/xxxxxxxxx/' . $converted_name . '_re_.mp4',
        ]);
    }`

**Comment by simpledev** [comment]
Have you checked in the php.ini file if upload_max_filesize and post_max_size are set correctly ?

**Comment by bruno9520** [comment]
Yes I upload the file correctly then I use this with job, the original file is uploaded, but when the jobs start If the file is bigger than 15mb I recive that error

**Comment by pascalbaljet** [comment]
What queue timeout values did you configure?

**Comment by bruno9520** [comment]
> What queue timeout values did you configure?

queue:work --tries=3 --timeout=1800

**Comment by pascalbaljet** [comment]
Does it work outside of the queueing system?

**Comment by bruno9520** [comment]
> Does it work outside of the queueing system?

I have not tried that let me check, however, this configuration was tested locally and it works perfectly, the problem occurs only in production

**Comment by pascalbaljet** [comment]
I'll close this issue as it seems unrelated to the package.
