### ISSUE TITLE
HLS

### ISSUE THREAD

**Issue by Aliakbari1994** [protonemedia/laravel-ffmpeg#250]
I output my audio file for HLS, but in the end the last 5 .ts files are executed and the content of m3u8 file is as follows:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:94
#EXTINF:1.992000,
o3Xv0P16048222885sLsiLTNnsekOQy0YteL94.ts
#EXTINF:1.992000,
o3Xv0P16048222885sLsiLTNnsekOQy0YteL95.ts
#EXTINF:2.016000,
o3Xv0P16048222885sLsiLTNnsekOQy0YteL96.ts
#EXTINF:1.992000,
o3Xv0P16048222885sLsiLTNnsekOQy0YteL97.ts
#EXTINF:0.751022,
o3Xv0P16048222885sLsiLTNnsekOQy0YteL98.ts
#EXT-X-ENDLIST

The .ts files ( 1 to 94 ) is not inserted and will not run.

**Comment by nemesisKO** [comment]
hi 
how did you export mp3 to hls? im struggling too
