### ISSUE TITLE
Unrecognized option 'hls_playlist_type'. Error splitting the argument list: Option not found

### ISSUE THREAD

**Issue by yasir-naseer-tetralogicx** [protonemedia/laravel-ffmpeg#252]
Im trying to export video to HLS using this piece of code 
```
$low = (new X264())->setKiloBitrate(100);
        $mid = (new X264())->setKiloBitrate(250);
        $high = (new X264())->setKiloBitrate(500);

        $str =  $this->video->path;

       FFMpeg::fromDisk('public')
            ->open($str)
            ->exportForHLS()
            ->addFormat($low, function($media) {
                $media->addFilter('scale=640:480');
            })
            ->addFormat($mid, function($media) {
                $media->scale(960, 720);
            })
            ->addFormat($high, function ($media) {
                $media->addFilter(function ($filters, $in, $out) {
                    $filters->custom($in, 'scale=1920:1200', $out); // $in, $parameters, $out
                });
            })
            ->save("public/videos/{$this->video->id}/{$this->video->id}.m3u8");
```

But i keep on getting this Error:
[2020-11-12 20:37:35] local.ERROR: Encoding failed {"exception":"[object] (ProtoneMedia\\LaravelFFMpeg\\Exporters\\EncodingException(code: 0): Encoding failed at C:\\xampp\\htdocs\\laratube\\vendor\\pbmedia\\laravel-ffmpeg\\src\\Exporters\\EncodingException.php:12)
[stacktrace]
#0 C:\\xampp\\htdocs\\laratube\\vendor\\pbmedia\\laravel-ffmpeg\\src\\Exporters\\MediaExporter.php(171): ProtoneMedia\\LaravelFFMpeg\\Exporters\\EncodingException::decorate(Object(FFMpeg\\Exception\\RuntimeException))
#1 C:\\xampp\\htdocs\\laratube\\vendor\\pbmedia\\laravel-ffmpeg\\src\\Exporters\\MediaExporter.php(129): ProtoneMedia\\LaravelFFMpeg\\Exporters\\MediaExporter->saveWithMappings()
#2 C:\\xampp\\htdocs\\laratube\\vendor\\pbmedia\\laravel-ffmpeg\\src\\Exporters\\HLSExporter.php(174): ProtoneMedia\\LaravelFFMpeg\\Exporters\\MediaExporter->save()
#3 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\EnumeratesValues.php(660): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSExporter->ProtoneMedia\\LaravelFFMpeg\\Exporters\\{closure}(Object(Illuminate\\Support\\Collection))
#4 C:\\xampp\\htdocs\\laratube\\vendor\\pbmedia\\laravel-ffmpeg\\src\\Exporters\\HLSExporter.php(184): Illuminate\\Support\\Collection->pipe(Object(Closure))
#5 C:\\xampp\\htdocs\\laratube\\app\\Jobs\\Video\\ConvertForStreaming.php(55): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSExporter->save('public/videos/e...')
#6 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): App\\Jobs\\Video\\ConvertForStreaming->handle()
#7 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#9 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#10 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#11 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#12 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\Video\\ConvertForStreaming))
#13 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Video\\ConvertForStreaming))
#14 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#15 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\Video\\ConvertForStreaming), false)
#16 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\Video\\ConvertForStreaming))
#17 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Video\\ConvertForStreaming))
#18 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(App\\Jobs\\Video\\ConvertForStreaming))
#20 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Jobs\\Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#21 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
#22 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(306): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#23 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(132): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#24 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#25 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#26 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#27 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#28 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#29 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#30 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#31 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(134): Illuminate\\Container\\Container->call(Array)
#32 C:\\xampp\\htdocs\\laratube\\vendor\\symfony\\console\\Command\\Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#33 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#34 C:\\xampp\\htdocs\\laratube\\vendor\\symfony\\console\\Application.php(920): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 C:\\xampp\\htdocs\\laratube\\vendor\\symfony\\console\\Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 C:\\xampp\\htdocs\\laratube\\vendor\\symfony\\console\\Application.php(142): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 C:\\xampp\\htdocs\\laratube\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 {main}

[previous exception] [object] (Alchemy\\BinaryDriver\\Exception\\ExecutionFailureException(code: 0): ffmpeg failed to execute command C:\\FFmpeg\\bin\\ffmpeg.EXE -y -threads 12 -i \"C:\\xampp\\htdocs\\laratube\\storage\\app/public\\channels/4c918fd7-1cf1-446a-88db-7e8ff4b01c37/jNMI55psfLFQ4NzckZQRWZv2v8V8soMf75H3dlyo.mp4\" -filter_complex [0]scale=640:480[v0_hls_1];[0]scale=960:720[v1_hls_1];[0]scale=1920:1200[v2_hls_1] -map [v0_hls_1] -map 0:a -vcodec libx264 -b:v 100k -g 48 -hls_playlist_type vod -hls_time 10 -hls_segment_filename \"C:\\xampp\\htdocs\\laratube\\storage\\app/public\\public/videos/e0adbebe-6054-4162-93c5-3e885ed89b89\\e0adbebe-6054-4162-93c5-3e885ed89b89_0_100_\"^%\"05d.ts\" -acodec libfaac -b:a 128k \"C:\\xampp\\htdocs\\laratube\\storage\\app/public\\public/videos/e0adbebe-6054-4162-93c5-3e885ed89b89\\e0adbebe-6054-4162-93c5-3e885ed89b89_0_100.m3u8\" -map [v1_hls_1] -map 0:a -vcodec libx264 -b:v 250k -g 48 -hls_playlist_type vod -hls_time 10 -hls_segment_filename \"C:\\xampp\\htdocs\\laratube\\storage\\app/public\\public/videos/e0adbebe-6054-4162-93c5-3e885ed89b89\\e0adbebe-6054-4162-93c5-3e885ed89b89_1_250_\"^%\"05d.ts\" -acodec libfaac -b:a 128k \"C:\\xampp\\htdocs\\laratube\\storage\\app/public\\public/videos/e0adbebe-6054-4162-93c5-3e885ed89b89\\e0adbebe-6054-4162-93c5-3e885ed89b89_1_250.m3u8\" -map [v2_hls_1] -map 0:a -vcodec libx264 -b:v 500k -g 48 -hls_playlist_type vod -hls_time 10 -hls_segment_filename \"C:\\xampp\\htdocs\\laratube\\storage\\app/public\\public/videos/e0adbebe-6054-4162-93c5-3e885ed89b89\\e0adbebe-6054-4162-93c5-3e885ed89b89_2_500_\"^%\"05d.ts\" -acodec libfaac -b:a 128k \"C:\\xampp\\htdocs\\laratube\\storage\\app/public\\public/videos/e0adbebe-6054-4162-93c5-3e885ed89b89\\e0adbebe-6054-4162-93c5-3e885ed89b89_2_500.m3u8\":

Error Output:

 ffmpeg version 2.5.2 Copyright (c) 2000-2014 the FFmpeg developers
  built on Dec 30 2014 17:23:26 with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Unrecognized option 'hls_playlist_type'.
Error splitting the argument list: Option not found
 at C:\\xampp\\htdocs\\laratube\\vendor\\alchemy\\binary-driver\\src\\Alchemy\\BinaryDriver\\ProcessRunner.php:95)
[stacktrace]
#0 C:\\xampp\\htdocs\\laratube\\vendor\\alchemy\\binary-driver\\src\\Alchemy\\BinaryDriver\\ProcessRunner.php(73): Alchemy\\BinaryDriver\\ProcessRunner->doExecutionFailure('C:\\\\FFmpeg\\\\bin\\\\f...', 'ffmpeg version ...')
#1 C:\\xampp\\htdocs\\laratube\\vendor\\alchemy\\binary-driver\\src\\Alchemy\\BinaryDriver\\AbstractBinary.php(207): Alchemy\\BinaryDriver\\ProcessRunner->run(Object(Symfony\\Component\\Process\\Process), Object(SplObjectStorage), false)
#2 C:\\xampp\\htdocs\\laratube\\vendor\\alchemy\\binary-driver\\src\\Alchemy\\BinaryDriver\\AbstractBinary.php(136): Alchemy\\BinaryDriver\\AbstractBinary->run(Object(Symfony\\Component\\Process\\Process), false, Array)
#3 C:\\xampp\\htdocs\\laratube\\vendor\\php-ffmpeg\\php-ffmpeg\\src\\FFMpeg\\Media\\AdvancedMedia.php(237): Alchemy\\BinaryDriver\\AbstractBinary->command(Array, false, Array)
#4 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php(23): FFMpeg\\Media\\AdvancedMedia->save()
#5 C:\\xampp\\htdocs\\laratube\\vendor\\pbmedia\\laravel-ffmpeg\\src\\Drivers\\PHPFFMpeg.php(175): ProtoneMedia\\LaravelFFMpeg\\Drivers\\PHPFFMpeg->forwardCallTo(Object(ProtoneMedia\\LaravelFFMpeg\\FFMpeg\\AdvancedMedia), 'save', Array)
#6 C:\\xampp\\htdocs\\laratube\\vendor\\pbmedia\\laravel-ffmpeg\\src\\Exporters\\MediaExporter.php(169): ProtoneMedia\\LaravelFFMpeg\\Drivers\\PHPFFMpeg->__call('save', Array)
#7 C:\\xampp\\htdocs\\laratube\\vendor\\pbmedia\\laravel-ffmpeg\\src\\Exporters\\MediaExporter.php(129): ProtoneMedia\\LaravelFFMpeg\\Exporters\\MediaExporter->saveWithMappings()
#8 C:\\xampp\\htdocs\\laratube\\vendor\\pbmedia\\laravel-ffmpeg\\src\\Exporters\\HLSExporter.php(174): ProtoneMedia\\LaravelFFMpeg\\Exporters\\MediaExporter->save()
#9 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\EnumeratesValues.php(660): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSExporter->ProtoneMedia\\LaravelFFMpeg\\Exporters\\{closure}(Object(Illuminate\\Support\\Collection))
#10 C:\\xampp\\htdocs\\laratube\\vendor\\pbmedia\\laravel-ffmpeg\\src\\Exporters\\HLSExporter.php(184): Illuminate\\Support\\Collection->pipe(Object(Closure))
#11 C:\\xampp\\htdocs\\laratube\\app\\Jobs\\Video\\ConvertForStreaming.php(55): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSExporter->save('public/videos/e...')
#12 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): App\\Jobs\\Video\\ConvertForStreaming->handle()
#13 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#15 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#16 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#17 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#18 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\Video\\ConvertForStreaming))
#19 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Video\\ConvertForStreaming))
#20 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#21 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\Video\\ConvertForStreaming), false)
#22 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\Video\\ConvertForStreaming))
#23 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Video\\ConvertForStreaming))
#24 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#25 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(App\\Jobs\\Video\\ConvertForStreaming))
#26 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Jobs\\Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#27 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
#28 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(306): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#29 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(132): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#30 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#31 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#32 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#33 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#34 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#35 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#36 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#37 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(134): Illuminate\\Container\\Container->call(Array)
#38 C:\\xampp\\htdocs\\laratube\\vendor\\symfony\\console\\Command\\Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#39 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#40 C:\\xampp\\htdocs\\laratube\\vendor\\symfony\\console\\Application.php(920): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 C:\\xampp\\htdocs\\laratube\\vendor\\symfony\\console\\Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 C:\\xampp\\htdocs\\laratube\\vendor\\symfony\\console\\Application.php(142): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 C:\\xampp\\htdocs\\laratube\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 C:\\xampp\\htdocs\\laratube\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 {main}
"}

**Comment by pascalbaljet** [comment]
You’re running an old version of FFmpeg that doesn’t support HLS. Update your binaries and you’re fine :)
