### ISSUE TITLE
AUDIO ARTWOARK METADATA

### ISSUE THREAD

**Issue by Aliakbari1994** [protonemedia/laravel-ffmpeg#253]
I am using laravel-ffmpeg Package and I want to put the image on the audio file. My code is as follows:

            $thumbnailUrl = Storage::disk('thumbnail')->path($thumbnailPath);
            $audioUploaded->filters()->addMetadata([
                "title" => $song->title_en,
                "artist" => "firs artist",
                "album" => 'album name',
                "album_artist" => 'second artist',
                "track" => 2,
                "year" => 2020,
                "genre" => 'persian',
                "comment" => 'comment',
                "artwork" => $thumbnailUrl
            ]);
But I make a mistake. How do I insert an image of an URL or file system disk into an audio file?

**Comment by pascalbaljet** [comment]
Check out this issue, you’ll find the answer there: https://github.com/protonemedia/laravel-ffmpeg/issues/237
