### ISSUE TITLE
alignment watermark ?

### ISSUE THREAD

**Issue by foremtehan** [protonemedia/laravel-ffmpeg#254]
Hello folks, Is there anything that set alignment for watermark ? I mean we have this positions in video:

![image](https://user-images.githubusercontent.com/53290883/99109184-a7f90300-25fd-11eb-9dd3-a0a3747dd4dd.png)

If it was set to 1 it doesn't matter what is video resolution it stick in bottom left corner

**Comment by pascalbaljet** [comment]
Check out [the documentation](https://github.com/protonemedia/laravel-ffmpeg#watermark-filter):

```php
FFMpeg::open('steve_howe.mp4')
    ->addWatermark(function(WatermarkFactory $watermark) {
        $watermark->open('logo.png')
            ->horizontalAlignment(WatermarkFactory::LEFT, 25)
            ->verticalAlignment(WatermarkFactory::TOP, 25);
    });
```
