### ISSUE TITLE
How to override or remove default filters ?

### ISSUE THREAD

**Issue by foremtehan** [protonemedia/laravel-ffmpeg#256]
I'm trying to apply my filters, But it look like it doesnt respect to my commands for example i want to set `-crf 28` which is a vbr encoding But it apply 1000k cbr bitrate at the end:

```
FFMpeg::fromDisk('')->open('input.mp4')
            ->resize(640, 480)
            ->export()
            ->addFilter('-crf', 28)
            ->inFormat((new \FFMpeg\Format\Video\X264('aac'))->setAudioKiloBitrate(64))
            ->save('aha.mp4');
```

It ignore my command and enocode video as 1000k bitare, The output command :

```
-y -i input.mp4 -crf 28 -threads 12 -vcodec libx264 -acodec aac -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 64k -vf [in]scale=640:480 [out] -pass 2 -passlogfile Local\Temp\ffmpeg-passes5fb0e73383d71xc9ct/pass-5fb0e733842fb 
```

How can i delete some of those default params ? like -b:v 1000k ?

**Comment by pascalbaljet** [comment]
We can't change this due to the underlying library. There is a PR (https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/767) which should fix it. I'll leave this issue opened until the PR is merged.

**Comment by Abdulmanan0315** [comment]
I am also waiting for this so that we can also write our **whole** custom commands, and also just only using the input paths etc

**Comment by foremtehan** [comment]
Yeah this problem alone prevent me to use this package and it's so ridiculous

**Comment by pascalbaljet** [comment]
I'll try to come up with a solution so you can interact with the command before it hits the binary. Maybe something like this:

```php
->export()
->beforeSaving(function(array $commands) {
    // make a change...
    $commands = array_reverse($commands);

    return $commands;
})
->save('final.mp4');
```

**Comment by pascalbaljet** [comment]
I've just tagged v7.5.5 which allows you to change the commands with the `beforeSaving` method ([docs](https://github.com/protonemedia/laravel-ffmpeg#experimental))

**Comment by LukeMadhanga** [comment]
> I'll try to come up with a solution so you can interact with the command before it hits the binary. Maybe something like this:
> 
> ```
> ->export()
> ->beforeSaving(function(array $commands) {
>     // make a change...
>     $commands = array_reverse($commands);
> 
>     return $commands;
> })
> ->save('final.mp4');
> ```

This was it for me - I basically had to rewrite the generated command because I had two inputs, so the library assumed it knew what was best for me. Thanks for this
