### ISSUE TITLE
Text watermark ?

### ISSUE THREAD

**Issue by foremtehan** [protonemedia/laravel-ffmpeg#257]
I just simply want to put my channel name in the video, But it seems the it only apply image as input, So is it possible to get it to work ? 

https://stackoverflow.com/questions/38726370/ffmpeg-text-watermark-bottom-left/38728172

**Comment by pascalbaljet** [comment]
Try using custom filters:
https://github.com/protonemedia/laravel-ffmpeg#custom-filters
