### ISSUE TITLE
PHP 8.0 support 

### ISSUE THREAD

**Issue by Salman98** [protonemedia/laravel-ffmpeg#258]
any idea when the PHP 8.0 support will add to this ?

**Comment by pascalbaljet** [comment]
PR: https://github.com/protonemedia/laravel-ffmpeg/pull/248

**Comment by Salman98** [comment]
> PR: #248
@pascalbaljet this PR is merged already , have a look there. Thanks.
https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/782#event-4130012340

**Comment by pascalbaljet** [comment]
Fixed in v7.5.
