### ISSUE TITLE
[Windows] ffprobe path separator bug

### ISSUE THREAD

**Issue by Mordo95** [protonemedia/laravel-ffmpeg#263]
using the HLS export on Windows x64, I have this code I use for testing out ffmpeg;

```$lowBitrate = (new X264('aac'))->setKiloBitrate(250);
        $midBitrate = (new X264('aac'))->setKiloBitrate(500);
        $highBitrate = (new X264('aac'))->setKiloBitrate(1000);

        $video = Video::create();

        FFMpeg::fromDisk('public')
            ->open('uploads/demo.mp4')
            ->exportForHLS()
            ->addFormat($lowBitrate)
            ->addFormat($midBitrate)
            ->addFormat($highBitrate)
            ->toDisk('videos')
            ->save($video->id . '/demo.m3u8');
```

Ffmpeg works fine and generates the correct output, but there is an issue with ffprobe. The command generated for ffprobe is:
`"resources/ffmpeg/ffprobe.exe" -allowed_extensions ALL "D:\xampp\htdocs\mywanderlust\storage\app/videos\14\demo_0_250.m3u8" -show_streams -print_format json`

which results in an exception `Unable to probe D:\xampp\htdocs\mywanderlust\storage\app/videos\14\demo_0_250.m3u8`.

I've tooled around with it myself a little bit and the cause is that the path ends with a backslash (14\demo_0...) instead of with a forward slash (14/demo_0...).

The shipped `Media` class does generate the path with a forward slash in the end, so I don't know where the last backslash comes from.

Edit: In HLSPlaylistGenerator on line 44: replacing it with the following line works:
```
$media = (new MediaOpener($playlistMedia->getDisk(), $driver))
                ->openWithInputOptions(str_replace('\\', '/', $playlistMedia->getPath()), ['-allowed_extensions', 'ALL']);
```

**Comment by pascalbaljet** [comment]
Thanks for the heads up! I've added Windows to the test matrix and I'll try to patch it soon:
https://github.com/protonemedia/laravel-ffmpeg/runs/1626159652

**Comment by Mordo95** [comment]
I've found a few more when trying to get rotating HLS encoding to work.

EncryptHLSSegments.php line 138-140, fix:
```
implode(PHP_EOL, [
                str_replace('\\', '/', $keyPath), $keyPath, $this->encryptionIV,
            ])
```

EncryptHLSSegments.php line 189:
```
$opensEncryptedSegment = Str::contains($line, "Opening 'crypto:")
```

EncryptHLSSegments.php line 224-228:
```
$content = str_replace(
                $prefix . str_replace('\\', '/', $this->encryptionSecretsDisk->path('')),
                $prefix,
                $disk->get($path)
            );
```

DynamicHLSPlaylist line 182:
```
preg_match_all('/#EXT-X-KEY:METHOD=AES-128,URI="([a-zA-Z0-9-_\/:]+.key)",IV=[a-z0-9]+/', $line, $matches);
```

This way I managed to get as well HLS encoding, rotating keys encryption and dynamic playback, to work.

**Comment by pascalbaljet** [comment]
> The shipped `Media` class does generate the path with a forward slash in the end, so I don't know where the last backslash comes from.

It comes from Flysystem's `AbstractAdapter`:
https://github.com/thephpleague/flysystem/blob/1.x/src/Adapter/AbstractAdapter.php#L17

**Comment by pascalbaljet** [comment]
> Another weird issue is the binary from ffprobe seems to be different from builds on different providers. The one from ffbuilds only seems to open the keyfiles from the relative directory, even if an absolute directory is given. The builds from gyan.dev work nicely and I would recommend testing them against that one.

This problem seems to be related with the working directory. I'm working on a fix but I've got still a bunch of tests failing:

https://github.com/protonemedia/laravel-ffmpeg/pull/265/files
https://github.com/protonemedia/laravel-ffmpeg/runs/1628441652?check_suite_focus=true

**Comment by pascalbaljet** [comment]
I just tagged v7.5.2 which should solve this problem.
