### ISSUE TITLE
laravel ffmpeg watermark is not working

### ISSUE THREAD

**Issue by webcoweb** [protonemedia/laravel-ffmpeg#269]
Hi
this error shows for me

`Argument 2 passed to FFMpeg\Filters\Video\WatermarkFilter::apply() must be an instance of FFMpeg\Format\VideoInterface, instance of ProtoneMedia\LaravelFFMpeg\FFMpeg\NullFormat given, called in C:\xampp\htdocs\myproject\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Media\AbstractVideo.php on line 157`

my code is 

```
use ProtoneMedia\LaravelFFMpeg\Filters\WatermarkFactory;
use ProtoneMedia\LaravelFFMpeg\Support\FFMpeg;

FFMpeg::fromDisk('media-ffmpeg-disk')->open('1.mp4')
->addWatermark(function(WatermarkFactory $watermark) {
    $watermark->fromDisk('media-ffmpeg-disk')->open('logo-watermark.png')
        ->right(25)
        ->bottom(25)
        ->width(100)
        ->height(100)
        ->greyscale();
})->export()->toDisk('media-ffmpeg-disk')->save('2.mp4');
```

and source code of line 157 from **\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Media\AbstractVideo.php** is :

```
        foreach ($filters as $filter) {
            $commands = array_merge($commands, $filter->apply($this, $format));
        }
```

Please Help me

**Comment by pascalbaljet** [comment]
You forgot to add a export format:

```php
export()
    ->toDisk('media-ffmpeg-disk')
    ->inFormat(new \FFMpeg\Format\Video\X264)
    ->save('2.mp4');
```
