### ISSUE TITLE
Syntax error in  vendor/pbmedia/laravel-ffmpeg/src/Support/ServiceProvider.php ?

### ISSUE THREAD

**Issue by kurumbus** [protonemedia/laravel-ffmpeg#270]
When I add package, I get 
`syntax error, unexpected ')'`
on every page. 

When I remove the comma it goes away, but is it supposed to be like that?

![image](https://user-images.githubusercontent.com/13556916/104552486-fd777d80-5649-11eb-91f7-33364af2ac2f.png)

Laravel 8 / PHP 7.2 / Windows 10

**Comment by pascalbaljet** [comment]
PHP 7.2 is not supported on Laravel 8:
https://laravel.com/docs/8.x/deployment#server-requirements

**Comment by imrantune** [comment]
Also facing same error on PHP 7.4.12 / laravel  6.20.9  and window 10

**Comment by sudiptochoudhury** [comment]
Hi, is there a way you can add more php versions like 7.2 to php support list along with `7.3|8.0`? 
Also, if you do, please remove the trailing parameter space in `ServiceProvider.php`
