### ISSUE TITLE
Use custom codec for audio files

### ISSUE THREAD

**Issue by kurumbus** [protonemedia/laravel-ffmpeg#271]
This is more php-ffmpeg issue, but still:

So php-ffmpeg video formats (vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Format/Video) take $audioCodec in a constructor:
```
  public function __construct($audioCodec = 'libfaac', $videoCodec = 'libx264')
    {
        $this
            ->setAudioCodec($audioCodec)
            ->setVideoCodec($videoCodec);
    }
```

But audio files just use default one like here: vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Format/Audio/Mp3.php
```
    public function __construct()
    {
        $this->audioCodec = 'libmp3lame';
    }
```

It means I need to fork php-ffmpeg and then fork laravel-ffmpeg and then use my php-pffmpeg as a dependency for my laravel-ffmpeg, right?

**Comment by kurumbus** [comment]
Update: 
well there's `setAudioCodec` function but it lets you choose from what's available

```
    /**
     * {@inheritDoc}
     */
    public function getAvailableAudioCodecs()
    {
        return array('libfdk_aac');
    }
```

So my problem is I want to `(new \FFMpeg\Format\Audio\Aac)->setAudioCodec('aac')` and it won't let me

**Comment by pascalbaljet** [comment]
You can create your own format class that extends `DefaultAudio`:

```php
use FFMpeg\Format\Audio\DefaultAudio;

class Aac extends DefaultAudio
{
    public function __construct()
    {
        $this->audioCodec = 'aac';
    }

    public function getAvailableAudioCodecs()
    {
        return ['aac'];
    }
}
```

**Comment by kurumbus** [comment]
Awesome thank you! 
I should have guessed.
