### ISSUE TITLE
unable to probe localAddress/file.m3u8

### ISSUE THREAD

**Issue by hazhir027** [protonemedia/laravel-ffmpeg#276]
here I faced to an error which I have no idea to fix:

ProtoneMedia\LaravelFFMpeg\FFMpeg\FFProbe::probeStreams E:\laravel\iptv workspace\IPTV-Lara-v8.x\vendor\pbmedia\laravel-ffmpeg\src\FFMpeg\FFProbe.php:121

it can't to getFFProbeDriver .

**Comment by pascalbaljet** [comment]
Can you share your code? And what version of PHP, Laravel and the package are you running?

**Comment by hazhir027** [comment]
hi there.

**Comment by hazhir027** [comment]
php version : 7.4.12
laravel version :Laravel Framework 8.20.1
![binaries-conf](https://user-images.githubusercontent.com/35688262/105627296-55349680-5e4b-11eb-88e9-dea43dcfa8e0.jpg)
![save-functionjpg](https://user-images.githubusercontent.com/35688262/105627300-5bc30e00-5e4b-11eb-836f-29ae417d61c1.jpg)
![storage-path](https://user-images.githubusercontent.com/35688262/105627301-5fef2b80-5e4b-11eb-881e-c473285a899e.jpg)
![error](https://user-images.githubusercontent.com/35688262/105627487-6c27b880-5e4c-11eb-8573-59faf16a2056.jpg)

**Comment by pascalbaljet** [comment]
And the version of Laravel FFmpeg? v7.5.2 fixed some errors on Windows specifically.

**Comment by hazhir027** [comment]
how can I found the Laravel FFmpeg version? I just install the package by default:

**Comment by pascalbaljet** [comment]
`composer show -- pbmedia/laravel-ffmpeg`

**Comment by hazhir027** [comment]
according to to top command :

**Comment by pascalbaljet** [comment]
`composer update` and make sure you’re on the latest version (v7.5.5)

**Comment by hazhir027** [comment]
Wow, great.
it fixed my problem. thank you so much.
