### ISSUE TITLE
hls encryption with key not working

### ISSUE THREAD

**Issue by seday72** [protonemedia/laravel-ffmpeg#279]
I got this error msg

`Unable to probe E:/work/.../index_0_250.m3u8`
E:\work...\vendor\pbmedia\laravel-ffmpeg\src\FFMpeg\FFProbe.php
line 121

My code is like this

                $lowBitrate = (new X264('aac'))->setKiloBitrate(250);
                $midBitrate = (new X264('aac'))->setKiloBitrate(500);
                $highBitrate = (new X264('aac'))->setKiloBitrate(1000);
                $encryptionKey = HLSExporter::generateEncryptionKey();

                FFMpeg::fromDisk('uploads')
                    ->open($modified_name)
                    ->exportForHLS()
                    ->withEncryptionKey($encryptionKey)
                    ->addFormat($lowBitrate)
                    ->addFormat($midBitrate)
                    ->addFormat($highBitrate)
                    ->toDisk('uploads')
                    ->save('index.m3u8');

Please check this and let me know the solution.
Thanks

**Comment by pascalbaljet** [comment]
Which version of the package and FFmpeg are you running? Is `updates` A local disk?

**Comment by seyyedam7** [comment]
Hi
I have same issue
Package works fine with my disks when I'm using that without encryption key
but when i added encryption key; i faced with this error
![image](https://user-images.githubusercontent.com/51041077/144390988-7e18e223-fc9b-447d-a6e0-119b32910f0c.png)

php version: 7.4.12
laravel version: 8.74.0
laravel-ffmpeg: 7.5.12

And this is my code

![image](https://user-images.githubusercontent.com/51041077/144391527-1623042b-3caf-4448-ba76-97511292e8f0.png)
![image](https://user-images.githubusercontent.com/51041077/144391705-d43f05d4-8fbd-40a6-bdb1-489cf924ed86.png)

Any ideas?

Thanks in advance!!
