### ISSUE TITLE
adding watermark in latest version after converting it to a format showing command not found in failed job

### ISSUE THREAD

**Issue by dikshantrajput** [protonemedia/laravel-ffmpeg#283]
->addFormat($lowBitrateFormat, function($media) {
                $media->scale(426, 240);
                $media->addWatermark(function ($watermark) {
                    $watermark->open('logo.png')
                        ->top(15)
                        ->left(15);
                });
                $media->addLegacyFilter(function ($filters) {
                    $filters->resize(new \FFMpeg\Coordinate\Dimension(426, 240));
                });
            })

**Comment by dikshantrajput** [comment]
`->addFormat($lowBitrateFormat, function($media) {
$media->scale(426, 240);
$media->addWatermark(function ($watermark) {
$watermark->open('logo.png')
->top(15)
->left(15);
});
$media->addLegacyFilter(function ($filters) {
$filters->resize(new \FFMpeg\Coordinate\Dimension(426, 240));
});
})`

**Comment by pascalbaljet** [comment]
Please share the full code and error/exception.
