### ISSUE TITLE
from HLS to MP4

### ISSUE THREAD

**Issue by AN1BRA** [protonemedia/laravel-ffmpeg#286]
Hi, I'm trying to convert from `m3u8` into `mp4` with your package, the `m3u8` and its `ts` fragments are stored in an s3 disk (in same folder), i've tried something like
```
FFMpeg::fromDisk(config('s3'))
            ->('path_to_file.m3u8')
            ->export()
            ->inFormat(new X264('aac'))
            ->toDisk(config('s3'))
            ->save('path_to_out.mp4');
```

this throws an error 
```
[hls,applehttp @ 0x55c5ad7c6ec0] Failed to open segment 0 of playlist
[hls,applehttp @ 0x55c5ad7c6ec0] Error when loading first segment
'/tmp/e3ef7b80be9cc4f5/4d1a1918964f82cfba073dbe50132de4_d77c6f0f-b98c-4a7b-8906-91e2def06b45_20210215154936734.ts'
```

**Comment by AN1BRA** [comment]
I'm definitely doing something wrong I just can't seem to find the right documentation for this specific use-case

**Comment by AN1BRA** [comment]
I took a different approach, I used
```
FFMpeg::dynamicHLSPlaylist()
      ->fromDisk(config('s3'))
      ->setMediaUrlResolver(function ($mediaFilename) {
         return $this->storage->temporaryUrl($mediaFilename);
      })
```
but I don't know what to do from here. `$this->storage->temporaryUrl(...)` returns the correct `ts` url, but how to continue from here so I can convert it into `mp4` ?

**Comment by pascalbaljet** [comment]
Opening HLS playlist from a remote disk is not supported. Can you create a S3 URL to the HLS playlist? Maybe you can try the `openUrl` method, but I’m not sure.
