### ISSUE TITLE
A question on how to create time-lapse video

### ISSUE THREAD

**Issue by uziel-bueno** [protonemedia/laravel-ffmpeg#287]
Hello!

Thanks for have created this pretty useful package, I really appreciate it!

I'm having trouble creating a timelapse from a sequence of 10 images. I would like to create a video
using one image per frame, then I expect to have a 10 seconds video created.

This is code I wrote:

```php
$paths = [
    '2021-02-01-14-00-00.jpg',
    '2021-02-01-14-05-00.jpg',
    '2021-02-01-14-10-00.jpg',
    '2021-02-01-14-15-00.jpg',
    '2021-02-01-14-20-00.jpg',
    '2021-02-01-14-25-00.jpg',
    '2021-02-01-14-35-00.jpg',
    '2021-02-01-14-40-00.jpg',
    '2021-02-01-14-45-00.jpg',
    '2021-02-01-14-50-00.jpg',
];

$outputPath = 'timelapse/my-timelapse.mp4';

FFMpeg::fromDisk('photos')
      ->open($paths)
      ->export()
      ->toDisk('videos')
      ->asTimelapseWithFramerate(1)
      ->addFormatOutputMapping(new X264, Media::make('videos', $outputPath), [
             '0:v', '1:v', '2:v', '3:v', '4:v', '5:v', '6:v', '7:v', '8:v', '9:v'
      ])
      ->save();

FFMpeg::cleanupTemporaryFiles();
```

According to the documentation it says that when multiple inputs are used a mapping from inputs to outputs must be specified. The thing is that it is creating the video file but with a length of 0 seconds.

Is there something I'm missing in the mappings part?

Do you know if `-pattern_type glob` is supported?

I'd really appreciate your advice on this topic.

**Comment by pascalbaljet** [comment]
You should not give it every path to every image, but you should give it just *one* pattern. I didn’t test it, but maybe you could try something like this:

`%04d-%02d-%02d-%02d-%02d-%02d.jpg` 

Check out the docs as well:
https://github.com/protonemedia/laravel-ffmpeg#create-a-timelapse

**Comment by uziel-bueno** [comment]
Hello @pascalbaljet 

I see what you mean. I thought that it can merge many input streams to an output. I was doing it like that because photos
come from the database and only a subset of photos (filtered by a date range) are used to generate the video. All photos are stored in a single place in a cloud storage that's why I didn't want to use the pattern against that disk otherwise it will match all the stored photos.

I cloud do what I wanted by downloading only the photos I need first, then point FFMPEG to those photos using a pattern:

```php
// Video.php eloquent model

public function exportFromPhotos(Collection $photos)
{
    // Download needed files and mapping to name filenames without leading zeroes
    $paths = $photos->pluck('filename')->map(function ($filename) {
        return $this->camera->storagePath($filename);
    })
    ->map(function ($path, $index) {
        // Rename every photo like 3333cdcf-5020-4928-884f-f93009a9b73e_1.jpg
        $name = $this->uuid . '_' . $index . '.' . pathinfo($path)['extension'];

        // Download every photo to a temporary local disk
        Storage::disk('local')->put($name, Storage::disk('photos')->get($path));

        return $name;
    });

    $videoFilename = $this->uuid . '.' . self::FILE_EXTENSION;

    // Generate video using a pattern to match downloaded files...
    FFMpeg::fromDisk('local')
        ->open($this->uuid . '_' . '%d.jpg')
        ->export()
        ->toDisk('videos')
        ->asTimelapseWithFramerate(1)
        ->inFormat((new X264())->setKiloBitrate(1000)->setAdditionalParameters([
            '-vf', 'format=yuv420p', // Extends compatibility with most players
            '-tune', 'stillimage', // Tune for still images
        ]))
        // This is used to log the command used to generate the video. Is there a better approach?
        ->beforeSaving(function ($commands) use (&$command) {
            $command = $commands[0];

            return $commands;
        })
        ->save($this->camera->storagePath($videoFilename));

    FFMpeg::cleanupTemporaryFiles();

    Storage::disk('local')->delete($paths);

    // Update video metadata in DB
    $this->update([
        'filename' => $videoFilename,
        'export_command' => collect($command)->values()->toJson(),
        'mimetype' => Storage::disk('videos')->mimeType($this->camera->storagePath($this->filename)),
        'size' => Storage::disk('videos')->size($this->camera->storagePath($this->filename)),
        'url' => Storage::disk('videos')->url($this->camera->storagePath($this->filename)),
        'export_finished_at' => $this->freshTimestamp(),
    ]);

    return $this;
}
```

Finally I think it would be very useful to be able to give it some paths of images and merge all into a single video. 
I tried to do it using ffmpeg directly without luck maybe I need a better understanding on how inputs and mapping works.

Much appreciated Pascal!

**Comment by pascalbaljet** [comment]
> Finally I think it would be very useful to be able to give it some paths of images and merge all into a single video.
> I tried to do it using ffmpeg directly without luck maybe I need a better understanding on how inputs and mapping works.

You can create a file with all the image paths, and use that file as an FFmpeg input:
https://trac.ffmpeg.org/wiki/Concatenate

Not sure if this is supported by this package, but that would be a great feature!
