### ISSUE TITLE
Probably a bug - Calculation of progress while dividing the file into parts.

### ISSUE THREAD

**Issue by Babiute** [protonemedia/laravel-ffmpeg#292]
I've probably found a bug in the package but Im not sure if its in this library or in the underlying library. Let me explain it.

I need to divide the file into parts and, for each part, I calculate the percentage of progress. The parcial code is bellow.

```
//use ProtoneMedia\LaravelFFMpeg\Support\FFMpeg;

$part = 1;
do {
        $video = Video::firstOrCreate(['name' => "video-part{$part}.mp4"]);
        FFMpeg::fromDisk('some_disk')
                ->open($file)
                ->export()
                ->onProgress(function ($percentage, $remaining, $rate) use ($video) {
                    $video->progress= $percentage;
                    $video->save();
                })
                ->toDisk('another_disc')
                ->inFormat($some_format)
                ->addFilter('-ss', TimeCode::fromSeconds($start))
                ->addFilter('-to', TimeCode::fromSeconds($start+ $this->clip_duration))
                ->save($video->name);
        $part++;
} while (condition);

```
The code is simplified but the parts that matter are there.
During the processing of the first part of the file, progress is persisted correctly and I can see it in the database:
video-part1.mp4 and the progress growing 10, 20, 30 ... 100.

But when the second part starts, which technically is a totally different video from the second (since it is executed after the save), progress is persisted for the current video and all previous ones. For example.

video-part1.mp4 and the progress growing 10, 20, 30 ... 100. (Start the progress again following the values ​​of the second)
video-part2.mp4 and the progress growing 10, 20, 30 ... 100.

video-part1.mp4 and the progress growing 10, 20, 30 ... 100. (Start the progress again following the values ​​of the third)
video-part2.mp4 and the progress growing 10, 20, 30 ... 100. (Start the progress again following the values ​​of the third)
video-par3.mp4 and the progress growing 10, 20, 30 ... 100.

and so on.

I checked the queries and the progress persistence query is triggered for each of the previous videos.

Its not one query overwriting the previous values. It is the query of each video being triggered again for the persistence of the progress values ​​of the current file.

After several tests with few mates in Laravel discord, we give up with this conclusion.

**
well, it must be that listeners remain and there's some kind of event that triggers all of them
as seen in the log, listeners are compounding
unless we are missing something, this is quite a big bug imo
the library should clean the listeners after the save call
so maybe worth creating a GH issue**

Note: everything else works as expected. The only problem is with the progress event.

thx for your help.

**Comment by pascalbaljet** [comment]
Could you try instantiating the format within the loop? (not reusing `$some_format`)

**Comment by Babiute** [comment]
Thx for your tip @pascalbaljet  and now its working like a charm.

Could u share why its working with your sugestion and why didnt in my way? So I can share it in the laravel discord community.

**Comment by pascalbaljet** [comment]
The underlying libraries binds the progress handler to the format. I don’t know why it was built this way, but maybe we could find a workaround. I’ll leave this issue opened until then :)

**Comment by pascalbaljet** [comment]
I've just tagged v7.5.6 with a patch.
