### ISSUE TITLE
Filter crf in HLS export

### ISSUE THREAD

**Issue by evilchis94** [protonemedia/laravel-ffmpeg#298]
Pascal, thanks for your amazing work!

I've been playing with HLS exports for VOD and I want to set -crf 20 to my different formats (320p, 720p and 1080p) but simply I just can't.

$lowFormat = (new X264('aac'))->setKiloBitrate(800)->setAudioKiloBitrate(96);
$mediumFormat = (new X264('aac'))->setKiloBitrate(2800);
$highFormat = (new X264('aac'))->setKiloBitrate(5000)->setAudioKiloBitrate(192);

    $this->info('Converting test.mp4');

    FFMpeg::fromDisk('uploads')
        ->open('test.mp4')
        ->exportForHLS()
        ->addFormat($lowFormat, function (HLSVideoFilters $filters) {
            $filters->resize(640, 320);
            // I have tried this $filters->addLegacyFilter(new FrameRateFilter(new FrameRate(20), 48));
            // also this $filters->addFilter(["-crf", "20"]);
        })
        ->addFormat($mediumFormat, function (HLSVideoFilters $filters) {
            $filters->resize(1280, 720);
        })
        ->addFormat($highFormat)
        ->onProgress(function ($progress) {
            $this->info("Progress: {$progress}%");
        })
        ->toDisk('public')
        ->save('videos/test.m3u8');

    $this->info('Done!');
In many cases log says:

`[AVFilterGraph @ 0x7ff755e5ea80] No such filter: '-crf 20`

What am I doing wrong?

**Comment by evilchis94** [comment]
I also tried this

`$lowFormat  = (new X264('aac'))->setKiloBitrate(800)->setAudioKiloBitrate(96)->setAdditionalParameters(['-crf',  '20']);`

**Comment by evilchis94** [comment]
Finally I was able to do it this way

`$lowFormat  = (new X264('aac'))->setKiloBitrate(800)->setAudioKiloBitrate(96)->setAdditionalParameters(['-profile:v', 'main', '-crf', '20']);`

**Comment by kobato-chan1912** [comment]
> 

Thanks for this. I was able to add -crf by this way.
