### ISSUE TITLE
Key is always rotated when create encrypted HLS with multiple formats

### ISSUE THREAD

**Issue by marbocub** [protonemedia/laravel-ffmpeg#302]
The following example in the README.md, the generated HLSs cannot be decyrpt by using $encryptionKey.

```
$encryptionKey = HLSExporter::generateEncryptionKey();

FFMpeg::open('steve_howe.mp4')
    ->exportForHLS()
    ->withEncryptionKey($encryptionKey)
    ->addFormat($lowBitrate)
    ->addFormat($midBitrate)
    ->addFormat($highBitrate)
    ->save('adaptive_steve.m3u8');
```

When creating encrypted HLS with multiple output formats, the key is always rotated instead of using the key specified in the first argument of withEncryptionKey().

**Comment by pascalbaljet** [comment]
Merged in v7.5.7. Thanks!
