### ISSUE TITLE
during processing i always get this error: failed to open stream: No such file or directory...

### ISSUE THREAD

**Issue by serdarkok** [protonemedia/laravel-ffmpeg#304]
Hi there;

**My Configuration:** 
Ubuntu 18.04
PHP 7.4.15
Mysql 5.7.29
i5 9600K
16 GB Ram
256 SSD Sandisk

During the processing, i got error from queue (db: failed_jobs). If i start the process for first video, it's completed successfully. But i got this error for next videos. Sometimes i have got this error for first video as well. I tried changing some things, result is same: 
1- change thread number (3,6,12...)
2- I removed saving key filenames to db (insert)

How may i fix it? Thanks.

**Error:**
` ErrorException: file_put_contents(/tmp/b788dea30a67f7bf/813cc371ef73a1db.key): failed to open stream: No such file or directory in /media/xxxx/LD/http/fflaravel/vendor/pbmedia/laravel-ffmpeg/src/Exporters/EncryptsHLSSegments.php:160
`
**Queue job configuration:**
`public function __construct($video)
    {
        $_video = Video::where('id', $video)->first();
        $this->video = $_video;
    }

    public function handle()
    {
        // create some video formats...
        $lowBitrateFormat  = (new X264('aac', 'libx264'))->setKiloBitrate(100);
        $midBitrateFormat  = (new X264('aac', 'libx264'))->setKiloBitrate(600);
        $highBitrateFormat = (new X264('aac', 'libx264'))->setKiloBitrate(1200);

        // open the uploaded video from the right disk...
        FFMpeg::fromDisk('videos')
            ->open($this->video->original_name)

            // call the 'exportForHLS' method and specify the disk to which we want to export...
            ->exportForHLS()
            ->toDisk('streamable_videos')
            ->withRotatingEncryptionKey(function ($filename, $contents) {
                Storage::disk('keys')->put($filename, $contents);
                DB::table('keys')->insert([
                    'video_id' => $this->video->id,
                    'key' => $filename,
                ]);
            })
            ->inFormat(new X264('aac'))
            ->onProgress(function ($percentage) {
                $this->video->update([
                    'processTime' => $percentage,
                    'isStartingConvert' => 1,
                ]);
            })
            ->addFormat($lowBitrateFormat, function ($media){ $media->scale(640, 360);})
            ->addFormat($highBitrateFormat, function ($media){ $media->scale(1280, 720);})
            // call the 'save' method with a filename...
            ->save($this->video->id . '.m3u8');

        // update the database so we know the convertion is done!
        $this->video->update([
            'isConverted' => 1,
            'stream_url' => $this->video->id . '.m3u8',
        ]);
    }`

**Comment by pascalbaljet** [comment]
Fixed #278
