### ISSUE TITLE
File already exists at path: temporary_segment_playlist_0.m3u8 

### ISSUE THREAD

**Issue by firmanalislami** [protonemedia/laravel-ffmpeg#306]
Hai, i Have problem, when i want transcoding , get the error File already exists at path: temporary_segment_playlist_0.m3u8, can you help me?

` public function handle()
    {
        ini_set('memory_limit', '-1');
 

        $res240  = (new X264('aac'))->setKiloBitrate(200)->setVideoCodec('libx264');
        $res360  = (new X264('aac'))->setKiloBitrate(300)->setVideoCodec('libx264');
        $res480  = (new X264('aac'))->setKiloBitrate(600)->setVideoCodec('libx264');
        $res720 = (new X264('aac'))->setKiloBitrate(1600)->setVideoCodec('libx264');
        $res1080 = (new X264('aac'))->setKiloBitrate(1800)->setVideoCodec('libx264');

         FFMpeg::fromDisk($this->video->disk)
            ->open($this->video->path)
            ->exportForHLS()
            ->withRotatingEncryptionKey(function ($filename, $contents) {
                Storage::disk('oss')->put($filename, $contents);
            })
            ->onProgress(function ($percentage) {
                $this->video->update([
                    'percentage' => $percentage,
                    Log::info('HLS export', compact('percentage'))
                ]);
            })
            
            ->toDisk('oss')

        // we'll add different formats so the stream will play smoothly
        // with all kinds of internet connections...
        ->addFormat($res240, function($media) {
           
                $media->scale(352, 240);
         
        })
             ->addFormat($res360, function($media) {
          
                $media->scale( 480,360);
         
        })
            ->addFormat($res480, function($media) {
               
                    $media->scale( 858,480);
                
            })
            ->addFormat($res720, function($media) {
                   
                        $media->scale(1280, 720);
                        
                
                })
            ->addFormat($res1080, function($media) {
               
                    $media->scale(1920, 1080);
                
            })

        // call the 'save' method with a filename...
            ->save($this->video->original_name . '.m3u8');
        
        // update the database so we know the convertion is done!
        $this->video->update([
            'converted_for_streaming_at' => Carbon::now(),
        ]);
        FFMpeg::cleanupTemporaryFiles();
    }
}`

![Screen Shot 2021-03-17 at 15 13 12](https://user-images.githubusercontent.com/29229224/111435387-51c6d880-8733-11eb-9a2a-ed619c9861e4.png)

**Comment by johnpuddephatt** [comment]
Are you using cloud storage? If so see https://github.com/protonemedia/laravel-ffmpeg/issues/220 – you may need to add `'disable_asserts' => true` to your filesystem config if you're using S3 compatible storage

**Comment by OfficialMOODi** [comment]
@johnpuddephatt - I am getting the same error. After adding disable_asserts, the error went away leaving me with the following:

` production.ERROR: Return value of ProtoneMedia\LaravelFFMpeg\Exporters\HLSPlaylistGenerator::getStreamInfoLine() must be of the type string, null returned {"exception":"[object] (TypeError(code: 0): Return value of ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSPlaylistGenerator::getStreamInfoLine() must be of the type string, null returned at /app/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSPlaylistGenerator.php:58)`

My code is as follows:

`php 
Log::info('Processing '. $coursePart->video_path .'.' , ['id' => $coursePart->id]);
                $format = new X264('libmp3lame', 'libx264');
                $lowBitrate = ($format)->setKiloBitrate(250);
                $midBitrate = ($format)->setKiloBitrate(500);
                $highBitrate = ($format)->setKiloBitrate(1000);
                $newFileName = 'course-parts/'.$coursePart->slug.'/'. Str::random(20) . '.m3u8';

                FFMpeg::fromDisk('s3')
                    ->open($coursePart->video_path)
                    ->exportForHLS()
                    ->toDisk('content')
                    ->addFormat($lowBitrate)
                    ->addFormat($midBitrate)
                    ->addFormat($highBitrate)
                    ->save($newFileName);

                FFMpeg::cleanupTemporaryFiles();
                Log::info('Course Part Processed.' , ['id' => $coursePart->id]);`

**Comment by renepardon** [comment]
I use this with Minio, works perfectly @johnpuddephatt thank you!

**Comment by imrantune** [comment]
> Minio

I also getting same error after `'disable_asserts' => true`

**Comment by JanMisker** [comment]
I must say I do think it's an issue with this package, because as said in #220, in the `copyAllFromTemporaryDirectory` function it tries to write to an existing file on S3, i.e. to the source file. 
I don't think that source file changed while in the temp dir, so it shouldn't try to overwrite it imho. Besides unnecessary, it also requires bandwidth (=time) to upload the same file again.

**Comment by JanMisker** [comment]
Additionally... I just noticed that that `copyAllFromTemporaryDirectory` is called during each `save`. So when in a chain with multiple saves (e.g. resizing video + taking a screenshot), the files are uploaded/copied multiple times. The `'disable_asserts' => true` works for me as a workaround, but I'm guessing this incurs multiple uploads, costing bandwidth and time.

**Comment by pascalbaljet** [comment]
I've walked through the whole process of HLS export with remote disks, and there's a cleanup for the temporary playlists:
https://github.com/protonemedia/laravel-ffmpeg/blob/7.5.12/src/Exporters/HLSExporter.php#L226

This issue might occur with parallel exports due to some race condition, so I could refactor the key-based temporary playlist to something more unique, like a UUID:
https://github.com/protonemedia/laravel-ffmpeg/blob/7.5.12/src/Exporters/HLSExporter.php#L213

**Comment by pascalbaljet** [comment]
Should be fixed in v7.7.0. Could somebody confirm? Thanks!
