### ISSUE TITLE
Unable to add watermark to uploaded video

### ISSUE THREAD

**Issue by kashifanwar313** [protonemedia/laravel-ffmpeg#313]
Hi :)

thank you for the amazing package, i am using it first time and i am stuck in it, maybe i am doing something wrong. I am trying to add a watermark on a video so users couldn't download the original video. below is my code to upload a video first and then add watermark to that video:

    public function watermarkpost(Request $request)
    {

        if ($file = $request->file('watermark')) 
        {      
           $name = time().str_replace(' ', '', $file->getClientOriginalName());
           $file->move('assets/images/products',$name);           
        }
            FFMpeg::open(asset('assets/images/products/'.$name))->addWatermark(function(WatermarkFactory $watermark) {
                $watermark
                ->open(asset('assets/images/1571567292logo.png') )
                ->right(25)
                ->bottom(25);
            });
       
        // return asset('assets/images/products/'.$name);
    }
but i am getting below error:

    Alchemy\\BinaryDriver\\Exception\\ExecutableNotFoundException(code: 0): Executable not found, proposed : ffmpeg at F:\\xampp\\htdocs\\GeniusCart\\project\\vendor\\alchemy\\binary-driver\\src\\Alchemy\\BinaryDriver\\AbstractBinary.php:159)
Any help would be really appreciated

**Comment by pascalbaljet** [comment]
This has nothing to do with the watermark. You're missing the FFmpeg binaries :)

https://github.com/protonemedia/laravel-ffmpeg/wiki/Unable-to-load-FFProbe
