### ISSUE TITLE
Cut clip from video, CopyFormat

### ISSUE THREAD

**Issue by videositefree** [protonemedia/laravel-ffmpeg#315]
Hi, 
I`m update ffmpeg and i`m want use CopyFormat 

`$ffmpeg = \FFMpeg\FFMpeg::create();
            $video = $ffmpeg->open('1.mp4');
            $video->filters()->clip(\FFMpeg\Coordinate\TimeCode::fromSeconds(1), \FFMpeg\Coordinate\TimeCode::fromSeconds(45));
            $video->save(new CopyFormat, 's.mp4');`

`FFMpeg\Filters\Video\ClipFilter::apply(): Argument #2 ($format) must be of type FFMpeg\Format\VideoInterface, ProtoneMedia\LaravelFFMpeg\FFMpeg\CopyFormat given, called in ... \vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Media\AbstractVideo.php on line 157 `

how correct add filtrs for this code?

**Comment by pascalbaljet** [comment]
Could you try again with `ProtoneMedia\LaravelFFMpeg\FFMpeg\CopyVideoFormat`?

**Comment by videositefree** [comment]
Thanks for reply.
I checked your answer unfortunately the problem is still the same.

It is caused by trying to add a filter. Maybe you know how to properly add filtrs, I want cut first 30 seconds of video

**Comment by videositefree** [comment]
Any idea? 
This simply code works greate
`ffmpeg -ss [start] -i in.mp4 -t [duration] -c copy out.mp4`

**Comment by videositefree** [comment]
Please Closed. reinstall ffmpeg and okey.
