### ISSUE TITLE
Cleaning up temp also clear active files which are being used (in process)?

### ISSUE THREAD

**Issue by sbthemes** [protonemedia/laravel-ffmpeg#316]
I am using this package with remote files and recently I notice that temp folder is taking too much space.

So I found below function from doc.

`FFMpeg::cleanupTemporaryFiles();`

Now my question is if I run this function at interval of every hour, does it also clean any active files which user are processing at the moment?

What is best way to use this function periodically so it doesn't affect any active processes?

Something like only clear files which are 1 hour older or something similar.

As I am afraid it will delete active file which user processing which may break things.

**Comment by pascalbaljet** [comment]
You can only use the `cleanupTemporaryFiles` directly after processing a job as it only keeps track of temporary directories of the current process. Running it in a cronjob won’t do anything.
