### ISSUE TITLE
FPS issue . Output frame rate is too much high 250

### ISSUE THREAD

**Issue by anilani27** [protonemedia/laravel-ffmpeg#318]
How to set fps as 25 for all the duration video.

 $lowBitrateFormat = (new X264('libmp3lame', 'libx264','-r 25'))->setKiloBitrate(100);
              $compression = FFMpeg::fromDisk('public')
                 ->open($filename)
       //->getFrameFromSeconds(10)
                            ->addFilter(function ($filters) {
                   $filters->resize(new Dimension(480, 360));
              })
             ->export()
            ->toDisk('s3')
             ->inFormat($lowBitrateFormat)
             ->save($s3FilePath);

**Comment by pascalbaljet** [comment]
There is a `framerate` filter provided by the underlying library:

https://github.com/PHP-FFMpeg/PHP-FFMpeg#framerate
