### ISSUE TITLE
Signed URLs?

### ISSUE THREAD

**Issue by dalisalvatore** [protonemedia/laravel-ffmpeg#323]
Is is possible to use encrypted signed urls for m3u8 file? Like huge video sites? I'd be glad if you could help.

For example:

https://googlevideo.com/videoplayback?expire=121415221&ei=nUquYOfSEIucgAfKzLvoDQ&id=o-AIDVqebdxlcKZot&itag=251&source=youtube&requiressl=yes&mh=iq&mm=31,29&mn=sn-u0g3jxaa-5qce,sn-nv47lney&ms=au,rdu&mv=m&mvi=3&pcm2cms=yes&pl=20&initcwndbps=770000&vprv=1&mime=audio/webm&ns=DZDPuvc9ozVyQX1lYsSeBLAF&gir=yes&clen=8342645&dur=604.201&lmt=1621970512744574&mt=1622034775&fvip=5&keepalive=yes&fexp=24001373,24007246&c=WEB&txp=5511222&n=30Uh8dhkKuXy3w

Thanks in advance.

**Comment by pascalbaljet** [comment]
You can combine the `DynamicHLSPlaylist` class with Laravel Signed URL feature:

https://github.com/protonemedia/laravel-ffmpeg#protecting-your-hls-encryption-keys

https://laravel.com/docs/8.x/urls#signed-urls
