### ISSUE TITLE
ProtoneMedia\LaravelFFMpeg\Exporters\NoFormatException

### ISSUE THREAD

**Issue by fa66666** [protonemedia/laravel-ffmpeg#327]
![image](https://user-images.githubusercontent.com/46362400/120966815-5383c380-c799-11eb-8e22-73efd89dd4c6.png)
![image](https://user-images.githubusercontent.com/46362400/120966839-5bdbfe80-c799-11eb-8e86-cad52df7acc0.png)

**It's really annoying*

**Comment by pascalbaljet** [comment]
Please read the docs about HLS, you need to use the `addFormat` method.
