### ISSUE TITLE
I tried to clip the video in m3u8 format, but an error was reported

### ISSUE THREAD

**Issue by suzhiF** [protonemedia/laravel-ffmpeg#331]
![image](https://user-images.githubusercontent.com/46362400/122025048-9712a900-cdfb-11eb-9617-27e3779f7a57.png)

my code
![image](https://user-images.githubusercontent.com/46362400/122025106-a5f95b80-cdfb-11eb-91a6-358ce5056760.png)

 I think my code is wrong
What is the correct way to write it

**Comment by eliasjtg** [comment]
Same issue

**Comment by pascalbaljet** [comment]
I think you need the `trim` filter:

```php
->addFormat((new X264), function ($media) {
    $media->addFilter('trim=start=0:end=2');
})
```
