### ISSUE TITLE
Argument 1 passed to ProtoneMedia\LaravelFFMpeg\FFMpeg\AdvancedOutputMapping::apply() must be an instance of FFMpeg\Media\AdvancedMedia

### ISSUE THREAD

**Issue by suzhiF** [protonemedia/laravel-ffmpeg#332]
error :
![image](https://user-images.githubusercontent.com/46362400/122171074-e4515200-ceb1-11eb-89ad-c3d309f830b7.png)

my code:
![image](https://user-images.githubusercontent.com/46362400/122171150-fa5f1280-ceb1-11eb-94dd-dd8efa727031.png)

Is there something wrong with my code?
I intend to generate a preview file in.m3u8 format

**Comment by eliasjtg** [comment]
Same issue

**Comment by pascalbaljet** [comment]
If you're using the HLS export feature, you need to use the `addFormat` method to add filters:

Check out the docs:
https://github.com/protonemedia/laravel-ffmpeg#hls
