### ISSUE TITLE
Is it possible to use concat demuxer with external txt file?

### ISSUE THREAD

**Issue by seblavoie** [protonemedia/laravel-ffmpeg#334]
I am trying to use the concat demuxer by reading an external txt file to generate a slideshow with time durations, as explained here : https://trac.ffmpeg.org/wiki/Slideshow#Concatdemuxer. I am trying to wrap my head around how this would work with the actual API, but I feel like I'm missing something. 

Here's what the command looks like, taken from FFMPEG's documentation: 

```
ffmpeg -f concat -i input.txt -vsync vfr -framerate 8 -pix_fmt yuv420p output.mp4
```

So my question is, is it possible to do this with the actual API? If not, is there something I can help out with to make it doable? 

Thanks for the great work! ✌️

**Comment by pascalbaljet** [comment]
What have you tried so far? Maybe you can try something like this:

```php

$format = new \FFMpeg\Format\Video\X264;
$format->setAdditionalParamters(['-vsync', 'vfr', 'framerate', 8, '-pix_fmt', 'yuv420p']);

FFMpeg::open('input.txt')
    ->export()
    ->inFormat($format)
    ->save('output.mp4');
```
