### ISSUE TITLE
FFMpeg\Format\Video\X264 setAdditionalParameters method does not take filters into account when using exportForHLS

### ISSUE THREAD

**Issue by walla1987** [protonemedia/laravel-ffmpeg#336]
Hi, when calling the setAdditionalParamters(['-preset:v', 'ultrafast']) it does not seem to be adding the filters to the bitrate.

Here is a sample of my code and the output.
<img width="951" alt="Screenshot 2021-06-24 at 02 04 45" src="https://user-images.githubusercontent.com/70644238/123182904-ab584500-d490-11eb-8eab-d945f1dafa5d.png">

Here is the log from ffmpeg. As you can see -preset:v ultrafast is not added
<img width="1672" alt="Screenshot 2021-06-24 at 01 59 05" src="https://user-images.githubusercontent.com/70644238/123182567-089fc680-d490-11eb-86e0-4697fe560bd9.png">

**Comment by pascalbaljet** [comment]
Fixed in v7.5.12.
