### ISSUE TITLE
Return value of HLSPlaylistGenerator::getStreamInfoLine() must be of the type string, null returned

### ISSUE THREAD

**Issue by baltiksoft** [protonemedia/laravel-ffmpeg#339]
Export to HLS 
OS: CentOS 8
PHP: 7.3

local.ERROR: Return value of ProtoneMedia\LaravelFFMpeg\Exporters\HLSPlaylistGenerator::getStreamInfoLine() must be of the type string, null returned {"exception":"[object] (TypeError(code: 0): Return value of ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSPlaylistGenerator::getStreamInfoLine() must be of the type string, null returned at /home/NNN/sites/examples.com/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSPlaylistGenerator.php:58)
[stacktrace]

`FFMpeg::fromDisk('public')
->open($file)
->exportForHLS()
->toDisk('public')
->addFormat((new X264)->setKiloBitrate($bitrate))
->save('stream_file.m3u8');`

**Comment by pascalbaljet** [comment]
How can I replicate this issue?
