### ISSUE TITLE
How to convert audio to Aiff format?

### ISSUE THREAD

**Issue by HeyLeom** [protonemedia/laravel-ffmpeg#340]
Hi, I need to convert an audio from .wav to .aiff but I think that is not supported. How could Ido it?

**Comment by HeyLeom** [comment]
I solved my problem doing this:

in:  \vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Format\Audio
I copied the Wav.php file and renamed to Aiff.php and I have to change this two lines: 

1. `$this->audioCodec = 'pcm_s16le';`
2. `return array('pcm_s16le');`
to:
1. `$this->audioCodec = 'pcm_s16be';`
2. `return array('pcm_s16be');`

also in:  \vendor\composer
I edited this two files:
1. autoload_static.php
2. autoload_classmap.php
In the first one I added a new line like this:
`'FFMpeg\\Format\\Audio\\Aiff' => __DIR__ . '/..' . '/php-ffmpeg/php-ffmpeg/src/FFMpeg/Format/Audio/Aiff.php',`
In the second one I added this:
`'FFMpeg\\Format\\Audio\\Wav' => $vendorDir . '/php-ffmpeg/php-ffmpeg/src/FFMpeg/Format/Audio/Wav.php',`

And done, if I write this:
```
FFMpeg::fromDisk('public')
                        ->open($filename)
                        ->export()
                        ->toDisk('public')
                        ->inFormat(new \FFMpeg\Format\Audio\Aiff)
                        ->save($filenameAiff);
```
It works

**Comment by pascalbaljet** [comment]
You should't edit anything in the `vendor` directory. You can use the `setAudioCodec` on a format instead, or create your own class:

https://github.com/protonemedia/laravel-ffmpeg/issues/271
