### ISSUE TITLE
Connection refused - laravel 8 in deploy Ubuntu 20.04

### ISSUE THREAD

**Issue by Javier2021** [protonemedia/laravel-ffmpeg#344]
Hi, I need help on this:
I have deployed my laravel8 project on ubuntu 20.04, but when using Laravel-FFMPEG, I get this error:

`SQLSTATE[HY000] [2002] Connection refused (SQL: update `sessions` set `payload` = YTo3OntzOjY6Il90b2tlbiI7czo0MDoiT0JOdWxUSXN1c2tKVFd5aVBUYnZ2NWpIalpBU1pkY2IzSmxBSm1MQSI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319czozOiJ1cmwiO2E6MDp7fXM6OToiX3ByZXZpb3VzIjthOjE6e3M6MzoidXJsIjtzOjUzOiJodHRwczovL2JvaGVtaWFkZWxldHJhcy5jb20vYWRtaW4vYXYtY3Vyc29zL3ZpZGVvcy8zNCI7fXM6NTA6ImxvZ2luX3dlYl81OWJhMzZhZGRjMmIyZjk0MDE1ODBmMDE0YzdmNThlYTRlMzA5ODlkIjtpOjE7czoxNzoicGFzc3dvcmRfaGFzaF93ZWIiO3M6NjA6IiQyeSQxMCROdlBaa3BGSHpFY3RuS0dmMy5SN3RlZDBiMEd6VW1wOHgyTG9Fem5xQmc3NWcyS1FCUy9MdSI7czoyMToicGFzc3dvcmRfaGFzaF9zYW5jdHVtIjtzOjYwOiIkMnkkMTAkTnZQWmtwRkh6RWN0bktHZjMuUjd0ZWQwYjBHelVtcDh4MkxvRXpucUJnNzVnMktRQlMvTHUiO30=, `last_activity` = 1630381788, `user_id` = 1, `ip_address` = 209.45.103.244, `user_agent` = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 where `id` = 1cfPpxQQjrQxgHShmPSkfDPSIV0xemUDyp3ZWEzy)`

my directory permissions:

> -rw-r--r--   1 www-data www-data    220 Aug 29 01:07 .editorconfig
-rw-r--r--   1 www-data www-data   1012 Aug 31 01:22 .env
drwxr-xr-x   8 www-data www-data   4096 Aug 29 23:43 .git/
-rw-r--r--   1 www-data www-data    111 Aug 29 01:07 .gitattributes
-rw-r--r--   1 www-data www-data    395 Aug 29 01:07 .gitignore
drwxr-xr-x   3 www-data www-data   4096 Aug 29 06:04 .idea/
-rw-r--r--   1 www-data www-data    181 Aug 29 01:07 .styleci.yml
-rw-r--r--   1 www-data www-data   3780 Aug 29 01:07 README.md
drwxr-xr-x   9 www-data www-data   4096 Aug 29 01:07 app/
-rw-r--r--   1 www-data www-data   1686 Aug 29 01:07 artisan
drwxr-xr-x   3 www-data www-data   4096 Aug 29 01:07 bootstrap/
-rw-r--r--   1 www-data www-data   1933 Aug 29 01:07 composer.json
-rw-r--r--   1 www-data www-data 340866 Aug 29 06:30 composer.lock
drwxr-xr-x   2 www-data www-data   4096 Aug 31 01:37 config/
drwxr-xr-x   5 www-data www-data   4096 Aug 29 01:07 database/
lrwxrwxrwx   1 www-data www-data     21 Aug 29 19:09 estaseraoculta -> /usr/share/phpmyadmin/
drwxr-xr-x 675 www-data www-data  20480 Aug 29 06:36 node_modules/
-rw-r--r--   1 www-data www-data 524821 Aug 29 01:07 package-lock.json
-rw-r--r--   1 www-data www-data    717 Aug 29 01:07 package.json
-rw-r--r--   1 www-data www-data   1202 Aug 29 01:07 phpunit.xml
drwxr-xr-x   8 www-data www-data   4096 Aug 31 03:49 public/
drwxr-xr-x   7 www-data www-data   4096 Aug 29 01:07 resources/
drwxr-xr-x   2 www-data www-data   4096 Aug 29 01:07 routes/
-rw-r--r--   1 www-data www-data    563 Aug 29 01:07 server.php
drwxrwxrwx   6 www-data www-data   4096 Aug 29 01:07 storage/
-rw-r--r--   1 www-data www-data    662 Aug 29 01:07 tailwind.config.js
drwxr-xr-x   4 www-data www-data   4096 Aug 29 01:07 tests/
drwxrwxr-x  62 www-data www-data   4096 Aug 29 06:34 vendor/
-rw-r--r--   1 www-data www-data    749 Aug 29 01:07 webpack.mix.js

And .env
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=databases
DB_USERNAME=user
DB_PASSWORD=password

**Comment by pascalbaljet** [comment]
This problem has nothing to do with this package. Check your database settings.

**Comment by Javier2021** [comment]
Actually only when I use this package I get this error, if I comment the code related to this package, all my application works

**Comment by Javier2021** [comment]
I want to mention that I used this package in Windows 10, in local mode and it works perfectly, it only happens to me when I deploy in UBUNTU 20.04
