### ISSUE TITLE
webserver can not load ffmepg

### ISSUE THREAD

**Issue by nishtman1366** [protonemedia/laravel-ffmpeg#355]
hi
I want to use dynamicHLSPlaylist in my controller and everything works fine on local machine but when I try to use project on production server it throws this error:

FFMpeg\Exception\ExecutableNotFoundException: Unable to load FFMpeg in file .../FFMpegDriver.php on line 55

and of course when I use the library within jobs it works fine and  everything is ok.
it seems webserver can not find the executable. I have try to create a symlink from allowed path(s) to executable on server but it dosen`t work at all.

**Comment by pascalbaljet** [comment]
https://github.com/protonemedia/laravel-ffmpeg/wiki/Unable-to-load-FFProbe
