### ISSUE TITLE
Is there a way to use job batching?

### ISSUE THREAD

**Issue by LoaiDev** [protonemedia/laravel-ffmpeg#356]
In my project I am going to need to transform very long videos into encrypted hls. Since this takes a long time is there a way this process can be divided into smaller jobs since long lived jobs are not a good idea for various reasons (failuers/retries/long timeout) or to be processed by multiple machines or processes at once to speed things up.

**Comment by pascalbaljet** [comment]
I don't think this is possible. However, maybe you could split the original video into multiple segments first and then somehow afterward stitch the HLS playlists together. Interesting case though, I'll leave this issue open in case someone comes with a great idea.
