### ISSUE TITLE
Live streaming instead of on-demand possible?

### ISSUE THREAD

**Issue by analyserdmz** [protonemedia/laravel-ffmpeg#357]
Hello, thank you for this project!
I am wondering if it's possible to keep selected streams "alive", instead of making them "on demand". And I am explaining...

In some ffmpeg-based projects, there is an option to mark the selected streams as "live". Meaning, there is a FFMPEG process running permanently in the background, and when a new client requests that stream, it directs the client to that stream instead of creating a new process.

The meaning of this is to play live streams (HTTP) and re-stream them by using only one ffmpeg process, to multiple clients.

The following super artistic line explains:
HTTP Source Stream  is hosting a live stream -> Laravel-FFMPEG configured to get that stream -> One / Multiple client(s) can watch the stream [but even with no clients the stream remains alive, waiting for a client]

**Comment by pascalbaljet** [comment]
This is currently not possible: #118
