### ISSUE TITLE
CPU usage is around 400% during export to HLS even after setting the thread to 1

### ISSUE THREAD

**Issue by sornapudisuresh** [protonemedia/laravel-ffmpeg#360]
Hi,

I'm facing this issue since last few days, even after setting the thread limit to 1, I have a high end VPS having 8 cores and 30 threads, but even after setting the thread to 1 in configuration file, my cpu usage is raising upto 400% and failing with 503 error in between conversion, only half of the video got converted and showing 503 error in console, please advice what to do.

**Comment by pascalbaljet** [comment]
The HLS feature uses parallel processing, so I guess limiting the threads to 1 will result in 1 thread per process. I've double-checked whether the package correctly passes the configuration to the FFmpeg command, which is fine.

**Comment by pascalbaljet** [comment]
Maybe this can be fixed with this PR: https://github.com/protonemedia/laravel-ffmpeg/pull/330

I'll investigate!

**Comment by Lewiscowles1986** [comment]
Is there a way for this to use hardware encoding?

I Recently sped up my h265 encoding by using hardware encoding (assuming hardware decoding is automatic if available);

```
ffmpeg -hwaccel qsv -i $INPUTFILE -c:v hevc_qsv -load_plugin hevc_hw -c:a aac -ac 2 -preset slow -crf 32 $OUTPUTFILE
```

This does a few things beyond hardware acceleration and uses (AFAIK) Intel `hevc_qsv` from the `hevc_hw` plugin:

* converts audio to aac 2-channel, preserving 5.1 to avoid weird left-right issues.
* may lower quality with `crf 32`, as I think I understand it higher is more disk space; lower is less, but at a cost of quality.
* `preset slow` seems to help get the most bang out of that constant quality [source](https://superuser.com/a/1557090/368231) by spending the most time selecting an algorithm per-frame.

**Comment by sornapudisuresh** [comment]
> 

Thanks for your reply @pascalbaljet will see if https://github.com/protonemedia/laravel-ffmpeg/pull/330 resolves the problem.

**Comment by ibrainventures** [comment]
hi @pascalbaljet 
i am the pr creator of
https://github.com/protonemedia/laravel-ffmpeg/pull/330

What do you think about this option to control the ffmpeg CPU load
programmatic?

It is not a breaking change. If someone has not this option in the config
the default (out-of-the-box) setup is used.

I am using my patch on many different szenario with Horizon, extern encoder
Workers etc. .. No problem ..

**Comment by pascalbaljet** [comment]
I've just tagged v7.7.3 which has PR #330. You can now set the `ffmpeg.threads` configuration key to `false` so you can control it manually.

**Comment by ibrainventures** [comment]
@pascalbaljet
cool .. my type-conflict preventing autism is going nuts .. lol :-) .. but a good way to solve the option
