### ISSUE TITLE
 HLS encryption with key not working

### ISSUE THREAD

**Issue by seyyedam7** [protonemedia/laravel-ffmpeg#361]
Package works fine with my disks when I'm using that without encryption key
but when I added encryption key; I faced with this error
![image](https://user-images.githubusercontent.com/51041077/144390988-7e18e223-fc9b-447d-a6e0-119b32910f0c.png)

PHP version: 7.4.12
Laravel version: 8.74.0
laravel-ffmpeg: 7.5.12
FFmpeg: 4.2.3

And this is my code

![image](https://user-images.githubusercontent.com/51041077/144391527-1623042b-3caf-4448-ba76-97511292e8f0.png)
![image](https://user-images.githubusercontent.com/51041077/144391705-d43f05d4-8fbd-40a6-bdb1-489cf924ed86.png)

I checked the exact file path in error and file exists in path.

What is the problem?

Thanks in advance!!

**Comment by seyyedam7** [comment]
I'm still waiting for an answer. Is there anyone who can solve this problem?

**Comment by pascalbaljet** [comment]
Could you share the Flare error link?

**Comment by seyyedam7** [comment]
Yeah, here it is.
https://flareapp.io/share/LPdEevN7

**Comment by pascalbaljet** [comment]
Thanks for sharing, something seems off with the segment filenames. `adaptive_steve_0_500_"^%"05d.ts` should be `adaptive_steve_0_500_05d.ts`.

```ffmpeg running command C:\xampp\htdocs\my_laravel\MentorPrivacy\ffmpeg\ffmpeg.exe -y -threads 12 -i "C:/xampp/htdocs/my_laravel/MentorPrivacy/storage/app/uploaded/test.mp4" -map 0 -vcodec libx264 -b:v 500k -sc_threshold 0 -g 48 -hls_playlist_type vod -hls_time 10 -hls_segment_filename "C:/xampp/htdocs/my_laravel/MentorPrivacy/storage/app/converted/adaptive_steve_0_500_"^%"05d.ts" -master_pl_name temporary_segment_playlist_0.m3u8 -hls_key_info_file "C:/Users/seyyed/AppData/Local/Temp/8265e4ea98fc8697/hls_encryption.keyinfo" -hls_flags periodic_rekey -acodec aac -b:a 128k "C:/xampp/htdocs/my_laravel/MentorPrivacy/storage/app/converted/adaptive_steve_0_500.m3u8" -map 0 -vcodec libx264 -b:v 1000k -sc_threshold 0 -g 48 -hls_playlist_type vod -hls_time 10 -hls_segment_filename "C:/xampp/htdocs/my_laravel/MentorPrivacy/storage/app/converted/adaptive_steve_1_1000_"^%"05d.ts" -master_pl_name temporary_segment_playlist_1.m3u8 -hls_key_info_file "C:/Users/seyyed/AppData/Local/Temp/8265e4ea98fc8697/hls_encryption.keyinfo" -hls_flags periodic_rekey -acodec aac -b:a 128k "C:/xampp/htdocs/my_laravel/MentorPrivacy/storage/app/converted/adaptive_steve_1_1000.m3u8" -map 0 -vcodec libx264 -b:v 1500k -sc_threshold 0 -g 48 -hls_playlist_type vod -hls_time 10 -hls_segment_filename "C:/xampp/htdocs/my_laravel/MentorPrivacy/storage/app/converted/adaptive_steve_2_1500_"^%"05d.ts" -master_pl_name temporary_segment_playlist_2.m3u8 -hls_key_info_file "C:/Users/seyyed/AppData/Local/Temp/8265e4ea98fc8697/hls_encryption.keyinfo" -hls_flags periodic_rekey -acodec aac -b:a 128k "C:/xampp/htdocs/my_laravel/MentorPrivacy/storage/app/converted/adaptive_steve_2_1500.m3u8"```

**Comment by seyyedam7** [comment]
Thank you for your responsibility.
This problem only happens when I use HLS encryption, and it works fine without it, as I said before.
Can you say, how should I fix this?
I have to encrypt my videos on our host and there is no choice to me.

**Comment by pascalbaljet** [comment]
Is there any way you can test your code in a Unix environment? For example, with Laravel Homestead or Laravel Sail? Unfortunately, I can't replicate the issue on macOS, so I want to make sure it's a Windows-related bug (though the GitHub Action workflow runs fine on Windows).

**Comment by seyyedam7** [comment]
Yes, You were right.
I tested it on Linux server, and It works fine.
It's a Windows-related bug.
Is there anyway to fix this?

I'm using Windows 10 Enterprise LTSC version 1809

**Comment by AliBayat** [comment]
> 

its probably some problem with probe.. i am using it on windows and it works fine

**Comment by seyyedam7** [comment]
> > 
> 
> its probably some problem with probe.. i am using it on windows and it works fine

Can you share your version of Windows and probe?
I'll be thankful if you share probe's link to download...

**Comment by AliBayat** [comment]
> > > 
> > 
> > 
> > its probably some problem with probe.. i am using it on windows and it works fine
> 
> Can you share your version of Windows and probe? I'll be thankful if you share probe's link to download...

i am using windows 10 x64
and the ffmpeg version is as following:

ffmpeg version 2.2.14 Copyright (c) 2000-2015 the FFmpeg developers
  built on Mar 23 2015 22:12:30 with gcc 4.8.3 (GCC)
  configuration: --prefix=/opt/windows_64 --libdir=/opt/windows_64/lib64 --shlibdir=/opt/windows_64/lib64 --docdir=/opt/windows_64/doc/ffmpeg-2.2.14/html --mandir=/opt/windows_64/man --disable-debug --enable-shared --disable-static --enable-pthreads --enable-libtheora --enable-libvorbis --enable-gpl --enable-version3 --enable-postproc --enable-swscale --enable-avfilter --cross-prefix=x86_64-w64-mingw32- --enable-cross-compile --enable-gnutls --arch=x86_64 --target-os=mingw32 --enable-libmp3lame --enable-libx264 --enable-libopus
  libavutil      52. 66.100 / 52. 66.100
  libavcodec     55. 52.102 / 55. 52.102
  libavformat    55. 33.100 / 55. 33.100
  libavdevice    55. 10.100 / 55. 10.100
  libavfilter     4.  2.100 /  4.  2.100
  libswscale      2.  5.102 /  2.  5.102
  libswresample   0. 18.100 /  0. 18.100
  libpostproc    52.  3.100 / 52.  3.100
Hyper fast Audio and Video encoder


if you download the ffmpeg from their website, both ffmpeg and ffprobe will be installed: 
https://ffmpeg.org/download.html

**Comment by seyyedam7** [comment]
> > > > 
> > > 
> > > 
> > > its probably some problem with probe.. i am using it on windows and it works fine
> > 
> > 
> > Can you share your version of Windows and probe? I'll be thankful if you share probe's link to download...
> 
> i am using windows 10 x64 and the ffmpeg version is as following:
> 
> ffmpeg version 2.2.14 Copyright (c) 2000-2015 the FFmpeg developers built on Mar 23 2015 22:12:30 with gcc 4.8.3 (GCC) configuration: --prefix=/opt/windows_64 --libdir=/opt/windows_64/lib64 --shlibdir=/opt/windows_64/lib64 --docdir=/opt/windows_64/doc/ffmpeg-2.2.14/html --mandir=/opt/windows_64/man --disable-debug --enable-shared --disable-static --enable-pthreads --enable-libtheora --enable-libvorbis --enable-gpl --enable-version3 --enable-postproc --enable-swscale --enable-avfilter --cross-prefix=x86_64-w64-mingw32- --enable-cross-compile --enable-gnutls --arch=x86_64 --target-os=mingw32 --enable-libmp3lame --enable-libx264 --enable-libopus libavutil 52. 66.100 / 52. 66.100 libavcodec 55. 52.102 / 55. 52.102 libavformat 55. 33.100 / 55. 33.100 libavdevice 55. 10.100 / 55. 10.100 libavfilter 4. 2.100 / 4. 2.100 libswscale 2. 5.102 / 2. 5.102 libswresample 0. 18.100 / 0. 18.100 libpostproc 52. 3.100 / 52. 3.100 Hyper fast Audio and Video encoder
> 
> if you download the ffmpeg from their website, both ffmpeg and ffprobe will be installed: https://ffmpeg.org/download.html
> 
> keep in mind that you should enter the path to these tools in the config file

I've done this, but still doesn't work.
It probably depends on Windows 10 version.
I migrated to Unix environment (Laravel sail) and it finally works.
For reminding, my problem was only related to "HLS encryption with key" and the other parts of packages work fine if we configure them well

**Comment by pascalbaljet** [comment]
For future readers of this issue: v2.2 is _very_ old (7-8 years at this point). Always try to use a recent FFmpeg build.
