### ISSUE TITLE
Prevent downloading video

### ISSUE THREAD

**Issue by alizamani** [protonemedia/laravel-ffmpeg#363]
Hi guys, 
I want to use this package to convert videos to HLS streaming playlist and prevent downloading video by users.

Please let me know can I achieve to this by using this package ? or is there any other ways to prevent video downloading even without HLS ?

Thanks a lot

**Comment by pascalbaljet** [comment]
You can't entirely prevent people from downloading publicly available videos, but you can make it harder for them by using encrypted HLS: https://github.com/protonemedia/laravel-ffmpeg#encrypted-hls
