### ISSUE TITLE
add a text as watermark instead of image

### ISSUE THREAD

**Issue by mojanimator** [protonemedia/laravel-ffmpeg#366]
hi . dear developer. can i add a text inside video as watermark?
your example codes uses of images as watermark
can u add a method to use text with a color as watermark?

Thank u

**Comment by pascalbaljet** [comment]
Use can use the [drawtext](https://ffmpeg.org/ffmpeg-filters.html#drawtext-1) filter:

```php
FFMpeg::open('video.mp4')
    ->export()
    ->addFilter(["-vf", "drawtext=text='Watermark Text':x=10:y=10:fontsize=16:fontcolor=white"])
    ->inFormat(new \FFMpeg\Format\Video\X264)
    ->save('video_with_text.mp4');
```
