### ISSUE TITLE
Pink noise after save as m3u8

### ISSUE THREAD

**Issue by vhdm** [protonemedia/laravel-ffmpeg#367]
Hi, please help me 
![image](https://user-images.githubusercontent.com/14149777/147390826-b9169af3-934b-456e-8daa-e547c84ff30b.png)

and my code is

![image](https://user-images.githubusercontent.com/14149777/147390850-23f39b70-7b9a-4b43-ab8e-83e1802f0f5c.png)

**Comment by pascalbaljet** [comment]
What version of FFmpeg do you use?

**Comment by vhdm** [comment]
@pascalbaljet 

![image](https://user-images.githubusercontent.com/14149777/147481543-c1a7974f-26b9-44e6-8ab0-f6f2ca9396a5.png)

**Comment by pascalbaljet** [comment]
Can you share the video?
