### ISSUE TITLE
Error playing HLS from private bucket. Issue is on .ts files url.

### ISSUE THREAD

**Issue by jay2success** [protonemedia/laravel-ffmpeg#379]
Hello,

Thank you for this great package.
I am encoding to HLS on private bucket using Backblaze B2.
The FFmpeg encoding works great but when playing it has issue when loading the "ts" files.
I found the issue from network (google chrome inspect tool).
The .m3u8 file are loading fine.
I tested on local disk and its working fine.
I am aware that i must use the Storage temporaryUrl() when using private disk.
I didn't use encryption, to make it easier for testing.

Here is my code:
```return FFMpeg::dynamicHLSPlaylist()
            ->fromDisk($disk)
            ->open($videoPath)
            ->setMediaUrlResolver(function ($mediaFilename) use ($disk, $folder, $expireMinutes) {
                return Storage::disk($disk)->temporaryUrl(
                    "{$folder}/{$mediaFilename}", now()->addMinutes($expireMinutes)
                );
            })
            ->setPlaylistUrlResolver(function ($playlistFilename) use ($disk, $folder, $expireMinutes) {
                return Storage::disk($disk)->temporaryUrl(
                    "{$folder}/{$playlistFilename}", now()->addMinutes($expireMinutes)
                );
            });
```

My question are:
1. Is it possible playing hls from private bucket?
2. If possible, what is the right code?

Thank you for answering this. Have a nice day.

**Comment by pascalbaljet** [comment]
It's definitely possible, we've got an app running on a private [Scaleway S3](https://www.scaleway.com/en/object-storage/) bucket. Are you sure that the `$folder` variable is correct or even necessary?

**Comment by jay2success** [comment]
Hi,

Thanks for the answer.
The folder contains the folder path to the video file.
I am using folder to save the video file and save the path to the database.
The playlist is loading fine using the same folder using temporaryUrl().
But the ts files are not loaded with temporaryUrl().
When i tested the same code on public local disk, its working fine. 
So i am not sure why its not working on cloud disk.

**Comment by jay2success** [comment]
Hi,

I have found the issue and fixed it. 
To solve it, the "setPlaylistUrlResolver()" must be set to route, like your example, i am using url directly.
Thank you once again for your help and this great package.
Have a nice day.
