### ISSUE TITLE
how to access encrypted hls videos and keys stored on ftp server 

### ISSUE THREAD

**Issue by MohamedAbdel-wahed** [protonemedia/laravel-ffmpeg#383]
Hello
I am trying to implement encrypted hls with Laravel ffmpeg 
It works fine if i store videos and keys on the same domain but when I stored videos and secret keys on another ftp server , it gave me not found when i try to turn on the video by video js 

Thanks in advance 🙏

**Comment by pascalbaljet** [comment]
Use the `DynamicHLSPlaylist` class to transform your playlists:
https://github.com/protonemedia/laravel-ffmpeg#protecting-your-hls-encryption-keys
