### ISSUE TITLE
Some videos on the iPhone are reversed horizontally and vertically.

### ISSUE THREAD

**Issue by madstone-dev** [protonemedia/laravel-ffmpeg#390]
Hello 🙂
I am trying to upload a video through this package.
But some iPhone videos are uploaded at a 90 degree angle.
These videos get reversed direction with `getDimensions`

```php
$media = FFMpeg::fromDisk('public')
->open($localVideoPath);

$dimensions = $media
->getVideoStream()
->getDimensions();

// Some videos on the iPhone are reversed horizontally and vertically.
```

How do I rotate the image in the correct orientation?

**Comment by pascalbaljet** [comment]
There's a rotate filter in the underlying package:
https://github.com/PHP-FFMpeg/PHP-FFMpeg#rotate

**Comment by madstone-dev** [comment]
> There's a rotate filter in the underlying package: https://github.com/PHP-FFMpeg/PHP-FFMpeg#rotate

I know a rotate filter exists.
But, I don't know how rotated the video uploaded from the iPhone.

How do I know how much the video is rotated?

**Comment by nam-co** [comment]
Hi @madstone-dev I was wondering how did you resolve this?

**Comment by nam-co** [comment]
Hi @madstone-dev I figure out a hack to try to fix it, if the rotation exists, I invert width and height
```
        //CALCULARE RATIO AND SIZE
        $data = FFMpeg::open($file)->getVideoStream()->all();
        $rotation = $data['side_data_list'][0]['rotation'] ?? null;
        if(!empty($rotation) AND $rotation != 0 AND $rotation != 270){
            $widthTemp = $data['width']; $width = $data['height']; $height = $widthTemp;
        }
```
