### ISSUE TITLE
getFrameRate function returning wrong frame rate

### ISSUE THREAD

**Issue by nhnkl159** [protonemedia/laravel-ffmpeg#393]
https://github.com/protonemedia/laravel-ffmpeg/blob/50cd4ccfaed9fbdb33f87a325a76c42b1635606d/src/Support/StreamParser.php#L24

I tried to extract frames from a video and the avg_frame_rate was: "22489751/1878963"

because of the Str::before, the $frameRate variable was returning only the number: 22489751.

I suggest removing the "Str::before" as the explode inline 33 takes only the first 2 numbers.

**Comment by pascalbaljet** [comment]
Fixed in v8.1.1.
