### ISSUE TITLE
Change URI path in m3u8

### ISSUE THREAD

**Issue by serdarkok** [protonemedia/laravel-ffmpeg#394]
Hi pascal, you are amazing, thanks for this package.

Thanks to your project, I made a video converting project. But I will use the videos and key files on different servers (independent of laravel). I will keep the ts files on a cdn and the key files in a different user protected node.js api. Therefore, I need to add the key files as https://api-domain/keys/sample.key to the URI field of the auto-generated m3u8 files in your project. However, I need to do this automatically during the converting of the videos. How can I add a prefix URL to the URI parameter inside the m3u8 files created in your project?

Like this:
`#EXT-X-KEY:METHOD=AES-128,URI="https://sample-api/key/6596fd8d9c9ef119.key",IV=0x279e69d3b7e93b5ed967d40ac49cc259`

As I mentioned above, I need to exit Laravel after converting video.

Thanks for answer.

**Comment by pascalbaljet** [comment]
You need an implementation of the `DynamicHLSPlaylist`.
