### ISSUE TITLE
Undefined array key "streams"

### ISSUE THREAD

**Issue by kp-sst** [protonemedia/laravel-ffmpeg#409]
Undefined array key "streams" in laravel 9

**Comment by pascalbaljet** [comment]
Could share a code example?

**Comment by alhaji-aki** [comment]
`FFMpeg::fromFilesystem(TemporaryDirectory::buildDisk())
            ->open('folder/video.mp4')
            ->getFrameFromSeconds(10)
            ->export()
            ->save('frame.jpg');`

This is a snippet of what I am doing

**Comment by alhaji-aki** [comment]
![image](https://user-images.githubusercontent.com/19788708/177328609-c8b900d9-3520-4a2e-8ff1-0ba88ffeb259.png)

Here is an example of how my code looks like.

Investigating further I realized this error was comming from the underlying `php-ffmpeg` package.
I am using PHP 8.1 and Laravel 9.

**Comment by pascalbaljet** [comment]
Maybe it’s the slash at the beginning of the file path.

**Comment by alhaji-aki** [comment]
Sorry I wasn't able to update this. Even though I was able to get it to work, I found two issues
1. It turns out my files were not downloading before the processing started
2. also if the file contained subtitle(s) it failed
