### ISSUE TITLE
want new methods in this package which set New Frame Rate Per Second

### ISSUE THREAD

**Issue by pkfan** [protonemedia/laravel-ffmpeg#410]
I cannot find any method to set frame rates of videos

I mean, it is possible to add new method (function) to this library which can change frame rates of videos like (15 frames / 1 sec) OR (25 frames / 1 second)

**method such as**

$mediaObject =  FFMpeg::open('dynamic/lesson1.mp4');

**$mediaObject->setFrameRatePerSecond(25);**

If it is not possible, then please give me some idea that "how can i do it?)

**Comment by pascalbaljet** [comment]
There is a `framerate` filter in the underlying package:

https://github.com/PHP-FFMpeg/PHP-FFMpeg#framerate
