### ISSUE TITLE
cant store keys into database as mentioned in the doc.

### ISSUE THREAD

**Issue by athulrajdr** [protonemedia/laravel-ffmpeg#415]
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xA2a+bef...' for column 'key' at row 1 (SQL: insert into `secrets` (`video_id`, `file_name`, `key`) values (1, b7ecfc7bfa8fa777.key, �a+bef�-�����[�))

**Comment by athulrajdr** [comment]
FFMpeg::fromDisk($video->disk)->open($video->path)
            ->exportForHLS()
            ->setSegmentLength(5)
            ->withRotatingEncryptionKey(function ($filename, $contents) use ($video) {
                // Storage::disk('secrets')->put($filename, $contents);
                DB::table('secrets')->insert([
                    'video_id' => $video->id,
                    'file_name' => $filename,
                    'key' => $contents
                ]);
            })
,............
.......

**Comment by athulrajdr** [comment]
the `$contents ` return some unreadable values.

**Comment by athulrajdr** [comment]
issue resolved as i changed the column type to binary.

**Comment by rc1021** [comment]
@athulrajdr  Thank you for your suggestion.

```
public function up(): void
{
    Schema::create('hls_secrets', function (Blueprint $table) {
        $table->id();
        $table->foreignId('video_id');
        $table->string('filename');
        $table->binary('contents'); // changed the column type to binary.
    });
}
```
