### ISSUE TITLE
PHP deprecated: getDurationInMiliseconds() and getDurationInSeconds()

### ISSUE THREAD

**Issue by ignacio-dev** [protonemedia/laravel-ffmpeg#427]
When using `getDurationInMiliseconds()` and `getDurationInSeconds()` PHP throws this message:

> PHP Deprecated:  Implicit conversion from float 10983.333 to int loses precision

**Comment by francoism90** [comment]
I think it should be using float, instead of int. See #429

**Comment by ibrainventures** [comment]
i changed with my pr
https://github.com/protonemedia/laravel-ffmpeg/pull/403/files
so .. there is no silence :-)

**Comment by pascalbaljet** [comment]
Fixed in v8.2.0
