### ISSUE TITLE
withEncryptionKey

### ISSUE THREAD

**Issue by LIOU2021** [protonemedia/laravel-ffmpeg#436]
when i use this mehod, not create any key in project, is my problem ?
but withRotatingEncryptionKey is work ! thx

**Comment by pascalbaljet** [comment]
Can you share your code?

**Comment by LIOU2021** [comment]
i was comments this line now, and instead used "withRotatingEncryptionKey".
https://github.com/LIOU2021/laravel-ffmpeg/blob/master/app/Jobs/ConvertVideoForStreaming.php#L47
