### ISSUE TITLE
how to limit thumbnails count ?

### ISSUE THREAD

**Issue by magic-thomas** [protonemedia/laravel-ffmpeg#439]
Hi . First, Really Thanks for great package. 

I would like limit the count of thumbnail image. 

I am using exportFramesByInterval() for making thumbnails. 

I know, I can reduce it by controlling time interval , but that is not what I want. 

I don't need thumbnails for whole video. 

I need just thumbnails in starting part of video. 

How can I limit the thumbnails amount ?

**Comment by Jandelson** [comment]
Hi magic-thomas
You can use as follow
method: getFrame FromSeconds combined with a foreach or for.
Example:

`FFMpeg::open($file)->each([2, 4, 6], function ($ffmpeg, $seconds, $key) {
    $ffmpeg->getFrameFromSeconds($seconds)->export()->save("thumb_{$key}.png");
});`

This resolve your question?

**Comment by magic-thomas** [comment]
> 

Yes. That is goo solution.. Thanks.
