### ISSUE TITLE
ramsey/collection version issue when installing

### ISSUE THREAD

**Issue by tarunsamuel7** [protonemedia/laravel-ffmpeg#462]
![image](https://user-images.githubusercontent.com/52186437/210968803-4b8b987b-9b81-4709-b205-b8842b36b223.png)

Seems like I have to downgrade version of 'ramsey/collection' package, but that might make my app unstable.
Any workaround for this? Thanks.

**Comment by jwktje** [comment]
I have this too. I'm using `"laravel/framework": "^9.19",`
And I'm on PHP 8.1

**Comment by elfeffe** [comment]
I have the same issue.

PHP 8.1.13 
Laravel 9.48.0

Why not to upgrade to ramsey/collection 2?

**Comment by pascalbaljet** [comment]
Fixed in v8.3.0.
